insert into countries (name, city, state) values ('Russia', 'Novaya Mayna', null);
insert into countries (name, city, state) values ('Poland', 'Pisz', null);
insert into countries (name, city, state) values ('China', 'Longzhou', null);
insert into countries (name, city, state) values ('Pakistan', 'Ahmadpur Siāl', null);
insert into countries (name, city, state) values ('Saudi Arabia', 'Ar Rass', null);
insert into countries (name, city, state) values ('Venezuela', 'Porlamar', null);
insert into countries (name, city, state) values ('Philippines', 'Tarlac City', null);
insert into countries (name, city, state) values ('Republic of the Congo', 'Owando', null);
insert into countries (name, city, state) values ('Ireland', 'Rathdrum', null);
insert into countries (name, city, state) values ('Sri Lanka', 'Batticaloa', null);
insert into countries (name, city, state) values ('Greece', 'Káto Asítai', null);
insert into countries (name, city, state) values ('Indonesia', 'Cihaladan', null);
insert into countries (name, city, state) values ('Ukraine', 'Velykyy Klyuchiv', null);
insert into countries (name, city, state) values ('China', 'Jiangchuan', null);
insert into countries (name, city, state) values ('Philippines', 'Cantao-an', null);
insert into countries (name, city, state) values ('Mexico', 'Lazaro Cardenas', 'Sinaloa');
insert into countries (name, city, state) values ('Ireland', 'Ballivor', null);
insert into countries (name, city, state) values ('Brazil', 'Pedro Leopoldo', null);
insert into countries (name, city, state) values ('Czech Republic', 'Prachatice', null);
insert into countries (name, city, state) values ('Indonesia', 'Bulumulyo', null);
insert into countries (name, city, state) values ('Japan', 'Kōnan', null);
insert into countries (name, city, state) values ('Portugal', 'Vale de Madeiros', 'Viseu');
insert into countries (name, city, state) values ('Jordan', 'Kurayyimah', null);
insert into countries (name, city, state) values ('Afghanistan', 'Jurm', null);
insert into countries (name, city, state) values ('Sweden', 'Örebro', 'Örebro');
insert into countries (name, city, state) values ('Iran', 'Ḩājjīābād', null);
insert into countries (name, city, state) values ('Nicaragua', 'Wiwilí', null);
insert into countries (name, city, state) values ('Indonesia', 'Citatah Kaler', null);
insert into countries (name, city, state) values ('China', 'Shimen', null);
insert into countries (name, city, state) values ('Ukraine', 'Dvorichna', null);
insert into countries (name, city, state) values ('Indonesia', 'Banjar Buahan', null);
insert into countries (name, city, state) values ('China', 'Lincheng', null);
insert into countries (name, city, state) values ('Russia', 'Urus-Martan', null);
insert into countries (name, city, state) values ('South Africa', 'Eshowe', null);
insert into countries (name, city, state) values ('Croatia', 'Hodošan', null);
insert into countries (name, city, state) values ('Zimbabwe', 'Lupane', null);
insert into countries (name, city, state) values ('Peru', 'Alca', null);
insert into countries (name, city, state) values ('China', 'Guanshan', null);
insert into countries (name, city, state) values ('Russia', 'Sakharovo', null);
insert into countries (name, city, state) values ('Iran', 'Manūjān', null);
insert into countries (name, city, state) values ('Indonesia', 'Kandang Timur', null);
insert into countries (name, city, state) values ('Czech Republic', 'Lipník nad Bečvou', null);
insert into countries (name, city, state) values ('Brazil', 'Porto Velho', null);
insert into countries (name, city, state) values ('China', 'Luyi', null);
insert into countries (name, city, state) values ('France', 'Aime', 'Rhône-Alpes');
insert into countries (name, city, state) values ('South Africa', 'KwaMbonambi', null);
insert into countries (name, city, state) values ('France', 'Nancy', 'Lorraine');
insert into countries (name, city, state) values ('Russia', 'Vyaz’ma', null);
insert into countries (name, city, state) values ('Ireland', 'Cork', null);
insert into countries (name, city, state) values ('China', 'Pingshan', null);
insert into countries (name, city, state) values ('China', 'Sandaogou', null);
insert into countries (name, city, state) values ('China', 'Lantian', null);
insert into countries (name, city, state) values ('China', 'Xinshi', null);
insert into countries (name, city, state) values ('Kazakhstan', 'Zhambyl', null);
insert into countries (name, city, state) values ('Indonesia', 'Semiring', null);
insert into countries (name, city, state) values ('China', 'Datun', null);
insert into countries (name, city, state) values ('New Zealand', 'Pleasant Point', null);
insert into countries (name, city, state) values ('China', 'Shimen', null);
insert into countries (name, city, state) values ('Poland', 'Lipie', null);
insert into countries (name, city, state) values ('Canada', 'Blackfalds', 'Alberta');
insert into countries (name, city, state) values ('China', 'Jiangkou', null);
insert into countries (name, city, state) values ('Mexico', 'Morelos', 'Morelos');
insert into countries (name, city, state) values ('Indonesia', 'Anjirmuara', null);
insert into countries (name, city, state) values ('Poland', 'Pogórze', null);
insert into countries (name, city, state) values ('Ukraine', 'Obertyn', null);
insert into countries (name, city, state) values ('Belarus', 'Svislach', null);
insert into countries (name, city, state) values ('Sweden', 'Örebro', 'Örebro');
insert into countries (name, city, state) values ('China', 'Daciyao', null);
insert into countries (name, city, state) values ('China', 'Lümeng', null);
insert into countries (name, city, state) values ('Czech Republic', 'Šluknov', null);
insert into countries (name, city, state) values ('Serbia', 'Jevremovac', null);
insert into countries (name, city, state) values ('Sweden', 'Örebro', 'Örebro');
insert into countries (name, city, state) values ('Nigeria', 'Boje', null);
insert into countries (name, city, state) values ('China', 'Chengdong', null);
insert into countries (name, city, state) values ('South Sudan', 'Kajok', null);
insert into countries (name, city, state) values ('Philippines', 'Carmelo', null);
insert into countries (name, city, state) values ('Poland', 'Osielec', null);
insert into countries (name, city, state) values ('France', 'Rumilly', 'Rhône-Alpes');
insert into countries (name, city, state) values ('Mexico', 'Las Flores', 'Oaxaca');
insert into countries (name, city, state) values ('Indonesia', 'Curug', null);
insert into countries (name, city, state) values ('Indonesia', 'Sepatan', null);
insert into countries (name, city, state) values ('Indonesia', 'Sumber Tengah', null);
insert into countries (name, city, state) values ('United States', 'Erie', 'Pennsylvania');
insert into countries (name, city, state) values ('Cyprus', 'Meniko', null);
insert into countries (name, city, state) values ('Madagascar', 'Sahavato', null);
insert into countries (name, city, state) values ('Spain', 'Leon', 'Castilla - Leon');
insert into countries (name, city, state) values ('Thailand', 'Sadao', null);
insert into countries (name, city, state) values ('United States', 'Knoxville', 'Tennessee');
insert into countries (name, city, state) values ('Thailand', 'Kut Rang', null);
insert into countries (name, city, state) values ('Ethiopia', 'Harar', null);
insert into countries (name, city, state) values ('Sweden', 'Horred', 'Västra Götaland');
insert into countries (name, city, state) values ('China', 'Panzhuang', null);
insert into countries (name, city, state) values ('France', 'Annecy', 'Rhône-Alpes');
insert into countries (name, city, state) values ('China', 'Qiankeng', null);
insert into countries (name, city, state) values ('Finland', 'Lappeenranta', null);
insert into countries (name, city, state) values ('Slovenia', 'Lenart v Slov. Goricah', null);
insert into countries (name, city, state) values ('Vietnam', 'An Châu', null);
insert into countries (name, city, state) values ('Ukraine', 'Drahovo', null);
insert into countries (name, city, state) values ('China', 'Dongxing', null);
insert into countries (name, city, state) values ('Argentina', 'La Cruz', null);
insert into countries (name, city, state) values ('Barbados', 'Welchman Hall', null);
insert into countries (name, city, state) values ('Philippines', 'Pambuhan', null);
insert into countries (name, city, state) values ('Peru', 'San Antonio', null);
insert into countries (name, city, state) values ('Russia', 'Ust-Maya', null);
insert into countries (name, city, state) values ('France', 'Arpajon', 'Île-de-France');
insert into countries (name, city, state) values ('Indonesia', 'Mburukullu', null);
insert into countries (name, city, state) values ('Spain', 'Zamora', 'Castilla - Leon');
insert into countries (name, city, state) values ('Portugal', 'Meirinhas', 'Leiria');
insert into countries (name, city, state) values ('Colombia', 'Mogotes', null);
insert into countries (name, city, state) values ('Peru', 'Taurisma', null);
insert into countries (name, city, state) values ('Portugal', 'Astromil', 'Porto');
insert into countries (name, city, state) values ('Tanzania', 'Mtinko', null);
insert into countries (name, city, state) values ('Bangladesh', 'Tāngāil', null);
insert into countries (name, city, state) values ('Russia', 'Vesëlyy', null);
insert into countries (name, city, state) values ('China', 'Kuleqi', null);
insert into countries (name, city, state) values ('Argentina', 'Yerba Buena', null);
insert into countries (name, city, state) values ('Poland', 'Gryfino', null);
insert into countries (name, city, state) values ('Philippines', 'Panikian', null);
insert into countries (name, city, state) values ('Indonesia', 'Karangbaru', null);
insert into countries (name, city, state) values ('Iran', 'Takāb', null);
insert into countries (name, city, state) values ('Burkina Faso', 'Bobo-Dioulasso', null);
insert into countries (name, city, state) values ('Portugal', 'Sobreira', 'Braga');
insert into countries (name, city, state) values ('Belarus', 'Atolina', null);
insert into countries (name, city, state) values ('China', 'Datian', null);
insert into countries (name, city, state) values ('Thailand', 'Ratchaburi', null);
insert into countries (name, city, state) values ('China', 'Sanjia', null);
insert into countries (name, city, state) values ('Republic of the Congo', 'Owando', null);
insert into countries (name, city, state) values ('Kazakhstan', 'Tekeli', null);
insert into countries (name, city, state) values ('Ukraine', 'Pereval''noe', null);
insert into countries (name, city, state) values ('Zimbabwe', 'Mutoko', null);
insert into countries (name, city, state) values ('Syria', 'Tādif', null);
insert into countries (name, city, state) values ('Indonesia', 'Sumberrejo', null);
insert into countries (name, city, state) values ('Argentina', 'Pontevedra', null);
insert into countries (name, city, state) values ('Bulgaria', 'Kiten', null);
insert into countries (name, city, state) values ('China', 'Yuncheng', null);
insert into countries (name, city, state) values ('Indonesia', 'Talangbetutu', null);
insert into countries (name, city, state) values ('Canada', 'Marieville', 'Québec');
insert into countries (name, city, state) values ('Indonesia', 'Robatal', null);
insert into countries (name, city, state) values ('Peru', 'Olleros', null);
insert into countries (name, city, state) values ('Ukraine', 'Svyatogorsk', null);
insert into countries (name, city, state) values ('China', 'Luqiao', null);
insert into countries (name, city, state) values ('Egypt', 'Damietta', null);
insert into countries (name, city, state) values ('Indonesia', 'Potulando', null);
insert into countries (name, city, state) values ('Indonesia', 'Curahpacul Satu', null);
insert into countries (name, city, state) values ('Canada', 'Mont-Joli', 'Québec');
insert into countries (name, city, state) values ('Honduras', 'San Juan de Planes', null);
insert into countries (name, city, state) values ('Canada', 'Notre-Dame-de-l''Île-Perrot', 'Québec');
insert into countries (name, city, state) values ('Peru', 'Vilque', null);
insert into countries (name, city, state) values ('Syria', 'Arīḩā', null);
insert into countries (name, city, state) values ('Indonesia', 'Ekasapta', null);
insert into countries (name, city, state) values ('Australia', 'Eastern Suburbs Mc', 'New South Wales');
insert into countries (name, city, state) values ('Guinea', 'Kissidougou', null);
insert into countries (name, city, state) values ('Macedonia', 'Poroj', null);
insert into countries (name, city, state) values ('Greece', 'Kastélli', null);
insert into countries (name, city, state) values ('China', 'Yuewan', null);
insert into countries (name, city, state) values ('China', 'Yangzi Jianglu', null);
insert into countries (name, city, state) values ('France', 'Paris 20', 'Île-de-France');
insert into countries (name, city, state) values ('China', 'Dawusu', null);
insert into countries (name, city, state) values ('Indonesia', 'Lampihung', null);
insert into countries (name, city, state) values ('Mongolia', 'Tsenher', null);
insert into countries (name, city, state) values ('Norway', 'Molde', 'More og Romdal');
insert into countries (name, city, state) values ('Ireland', 'Fairview', null);
insert into countries (name, city, state) values ('Croatia', 'Peteranec', null);
insert into countries (name, city, state) values ('Kenya', 'Mumias', null);
insert into countries (name, city, state) values ('Ukraine', 'Berezovo', null);
insert into countries (name, city, state) values ('Ukraine', 'Rakiv Lis', null);
insert into countries (name, city, state) values ('Russia', 'Aykhal', null);
insert into countries (name, city, state) values ('Sweden', 'Stockholm', 'Stockholm');
insert into countries (name, city, state) values ('Sweden', 'Nora', 'Örebro');
insert into countries (name, city, state) values ('Ecuador', 'Quito', null);
insert into countries (name, city, state) values ('Portugal', 'Cabeço de Vide', 'Portalegre');
insert into countries (name, city, state) values ('Philippines', 'Santo Niño', null);
insert into countries (name, city, state) values ('Honduras', 'Santa Lucía', null);
insert into countries (name, city, state) values ('Indonesia', 'Krajan Satu', null);
insert into countries (name, city, state) values ('Japan', 'Iwai', null);
insert into countries (name, city, state) values ('Thailand', 'Sop Pong', null);
insert into countries (name, city, state) values ('Portugal', 'Gémeos', 'Braga');
insert into countries (name, city, state) values ('Indonesia', 'Simabur', null);
insert into countries (name, city, state) values ('Nigeria', 'Onueke', null);
insert into countries (name, city, state) values ('Finland', 'Siikainen', null);
insert into countries (name, city, state) values ('Greece', 'Koímisi', null);
insert into countries (name, city, state) values ('Philippines', 'Nagbukel', null);
insert into countries (name, city, state) values ('China', 'Tuzhu', null);
insert into countries (name, city, state) values ('Iran', 'Lāmerd', null);
insert into countries (name, city, state) values ('Venezuela', 'El Pao', null);
insert into countries (name, city, state) values ('Peru', 'Huayucachi', null);
insert into countries (name, city, state) values ('Indonesia', 'Maesan', null);
insert into countries (name, city, state) values ('China', 'Jingu', null);
insert into countries (name, city, state) values ('China', 'Zhaotong', null);
insert into countries (name, city, state) values ('China', 'Wulijie', null);
insert into countries (name, city, state) values ('Slovenia', 'Bakovci', null);
insert into countries (name, city, state) values ('Poland', 'Wiskitki', null);
insert into countries (name, city, state) values ('Ecuador', 'Catamayo', null);
insert into countries (name, city, state) values ('Portugal', 'Aviúges', 'Viseu');
insert into countries (name, city, state) values ('China', 'Houping', null);
insert into countries (name, city, state) values ('Palestinian Territory', 'Sinjil', null);
insert into countries (name, city, state) values ('Ecuador', 'Otavalo', null);
insert into countries (name, city, state) values ('United States', 'Springfield', 'Illinois');
insert into countries (name, city, state) values ('China', 'Shiziling', null);
insert into countries (name, city, state) values ('Russia', 'Nerchinsk', null);
insert into countries (name, city, state) values ('South Africa', 'Ballitoville', null);
insert into countries (name, city, state) values ('China', 'Lijiapu', null);
insert into countries (name, city, state) values ('Indonesia', 'Rantau', null);
insert into countries (name, city, state) values ('Bulgaria', 'Smolyan', null);
insert into countries (name, city, state) values ('China', 'Dasongshu', null);
insert into countries (name, city, state) values ('Morocco', 'Tan-Tan', null);
insert into countries (name, city, state) values ('United States', 'Raleigh', 'North Carolina');
insert into countries (name, city, state) values ('China', 'Danan', null);
insert into countries (name, city, state) values ('Indonesia', 'Pangkalan Kasai', null);
insert into countries (name, city, state) values ('Sweden', 'Örebro', 'Örebro');
insert into countries (name, city, state) values ('China', 'Wanli', null);
insert into countries (name, city, state) values ('Portugal', 'Esposende', 'Braga');
insert into countries (name, city, state) values ('Czech Republic', 'Herálec', null);
insert into countries (name, city, state) values ('Russia', 'Shalinskoye', null);
insert into countries (name, city, state) values ('China', 'Lanlongkou', null);
insert into countries (name, city, state) values ('Serbia', 'Bukor', null);
insert into countries (name, city, state) values ('Indonesia', 'Penebel', null);
insert into countries (name, city, state) values ('China', 'Heshan', null);
insert into countries (name, city, state) values ('Albania', 'Blerim', null);
insert into countries (name, city, state) values ('China', 'Ganquan', null);
insert into countries (name, city, state) values ('China', 'Zhaogezhuang', null);
insert into countries (name, city, state) values ('Russia', 'Derbent', null);
insert into countries (name, city, state) values ('Ukraine', 'Komysh-Zorya', null);
insert into countries (name, city, state) values ('Nigeria', 'Ochobo', null);
insert into countries (name, city, state) values ('China', 'Taocheng', null);
insert into countries (name, city, state) values ('Brazil', 'Itatinga', null);
insert into countries (name, city, state) values ('Czech Republic', 'Trmice', null);
insert into countries (name, city, state) values ('Russia', 'Malaya Purga', null);
insert into countries (name, city, state) values ('China', 'Suban', null);
insert into countries (name, city, state) values ('France', 'Lyon', 'Rhône-Alpes');
insert into countries (name, city, state) values ('Venezuela', 'Aroa', null);
insert into countries (name, city, state) values ('Pakistan', 'Sobhādero', null);
insert into countries (name, city, state) values ('Myanmar', 'Tharyarwady', null);
insert into countries (name, city, state) values ('Indonesia', 'Lamalewar', null);
insert into countries (name, city, state) values ('Argentina', 'San José de Jáchal', null);
insert into countries (name, city, state) values ('France', 'Le Havre', 'Haute-Normandie');
insert into countries (name, city, state) values ('Myanmar', 'Nay Pyi Taw', null);
insert into countries (name, city, state) values ('Indonesia', 'Petung', null);
insert into countries (name, city, state) values ('Indonesia', 'Ciladaeun', null);
insert into countries (name, city, state) values ('United States', 'Durham', 'North Carolina');
insert into countries (name, city, state) values ('Russia', 'Zhukovka', null);
insert into countries (name, city, state) values ('Colombia', 'Río de Oro', null);
insert into countries (name, city, state) values ('Indonesia', 'Sungaibengkal', null);
insert into countries (name, city, state) values ('Norway', 'Kongsvinger', 'Hedmark');
insert into countries (name, city, state) values ('Indonesia', 'Aeka', null);
insert into countries (name, city, state) values ('Philippines', 'Calabugao', null);
insert into countries (name, city, state) values ('Russia', 'Staryy Cherek', null);
insert into countries (name, city, state) values ('Malaysia', 'Melaka', 'Melaka');
insert into countries (name, city, state) values ('United States', 'New York City', 'New York');
insert into countries (name, city, state) values ('Georgia', 'Khashuri', null);
insert into countries (name, city, state) values ('China', 'Zhanbei', null);
insert into countries (name, city, state) values ('France', 'Chennevières-sur-Marne', 'Île-de-France');
insert into countries (name, city, state) values ('United States', 'Atlanta', 'Georgia');
insert into countries (name, city, state) values ('Philippines', 'Amuñgan', null);
insert into countries (name, city, state) values ('Indonesia', 'Cinunjang', null);
insert into countries (name, city, state) values ('Serbia', 'Perlez', null);
insert into countries (name, city, state) values ('Macedonia', 'Gorobinci', null);
insert into countries (name, city, state) values ('Indonesia', 'Kebonkalapa', null);
insert into countries (name, city, state) values ('Poland', 'Ozimek', null);
insert into countries (name, city, state) values ('Venezuela', 'La Luz', null);
insert into countries (name, city, state) values ('Indonesia', 'Ngluweng Dua', null);
insert into countries (name, city, state) values ('Czech Republic', 'Stará Huť', null);
insert into countries (name, city, state) values ('Bangladesh', 'Netrakona', null);
insert into countries (name, city, state) values ('Colombia', 'Mosquera', null);
insert into countries (name, city, state) values ('Russia', 'Semënov', null);
insert into countries (name, city, state) values ('Philippines', 'Kalamangog', null);
insert into countries (name, city, state) values ('Argentina', 'Añatuya', null);
insert into countries (name, city, state) values ('Tunisia', 'Mahdia', null);
insert into countries (name, city, state) values ('China', 'Sicheng', null);
insert into countries (name, city, state) values ('Philippines', 'East Migpulao', null);
insert into countries (name, city, state) values ('Brazil', 'Pedregulho', null);
insert into countries (name, city, state) values ('China', 'Sanxiang', null);
insert into countries (name, city, state) values ('France', 'Nantes', 'Pays de la Loire');
insert into countries (name, city, state) values ('China', 'Xinqiao', null);
insert into countries (name, city, state) values ('Indonesia', 'Mojoagung', null);
insert into countries (name, city, state) values ('Brazil', 'Boracéia', null);
insert into countries (name, city, state) values ('Tanzania', 'Tukuyu', null);
insert into countries (name, city, state) values ('Philippines', 'Upper San Mateo', null);
insert into countries (name, city, state) values ('Colombia', 'San Antonio', null);
insert into countries (name, city, state) values ('Kuwait', 'Ar Riqqah', null);
insert into countries (name, city, state) values ('Indonesia', 'Modosinal', null);
insert into countries (name, city, state) values ('Russia', 'Inya', null);
insert into countries (name, city, state) values ('Russia', 'Vavozh', null);
insert into countries (name, city, state) values ('Portugal', 'Monte Novo', 'Setúbal');
insert into countries (name, city, state) values ('Philippines', 'Gumaus', null);
insert into countries (name, city, state) values ('Norway', 'Kongsvinger', 'Hedmark');
insert into countries (name, city, state) values ('Indonesia', 'Banjar Tengahbelayu', null);
insert into countries (name, city, state) values ('Netherlands', 'Utrecht (stad)', 'Provincie Utrecht');
insert into countries (name, city, state) values ('Russia', 'Birobidzhan', null);
insert into countries (name, city, state) values ('Thailand', 'Phatthaya', null);
insert into countries (name, city, state) values ('Bangladesh', 'Ishurdi', null);
insert into countries (name, city, state) values ('China', 'Hongqiao', null);
insert into countries (name, city, state) values ('Brazil', 'Uruaçu', null);
insert into countries (name, city, state) values ('China', 'Siqian', null);
insert into countries (name, city, state) values ('Greece', 'Vathýlakkos', null);
insert into countries (name, city, state) values ('Philippines', 'Alfonso', null);
insert into countries (name, city, state) values ('Sierra Leone', 'Kassiri', null);
insert into countries (name, city, state) values ('Iran', 'Fūman', null);
insert into countries (name, city, state) values ('Greece', 'Perivóli', null);
insert into countries (name, city, state) values ('Canada', 'Rayside-Balfour', 'Ontario');
insert into countries (name, city, state) values ('China', 'Tongxing', null);
insert into countries (name, city, state) values ('Belarus', 'Blon’', null);
insert into countries (name, city, state) values ('Saudi Arabia', '‘Afīf', null);
insert into countries (name, city, state) values ('Philippines', 'Buyuan', null);
insert into countries (name, city, state) values ('Indonesia', 'Ciomas', null);
insert into countries (name, city, state) values ('Croatia', 'Lepoglava', null);
insert into countries (name, city, state) values ('Poland', 'Przodkowo', null);
insert into countries (name, city, state) values ('Indonesia', 'Wirodayan', null);
insert into countries (name, city, state) values ('Japan', 'Zushi', null);
insert into countries (name, city, state) values ('Argentina', 'Laprida', null);
insert into countries (name, city, state) values ('China', 'Hanjia', null);
insert into countries (name, city, state) values ('France', 'Marne-la-Vallée', 'Île-de-France');
insert into countries (name, city, state) values ('Russia', 'Zeya', null);
insert into countries (name, city, state) values ('China', 'Yinping', null);
insert into countries (name, city, state) values ('Nigeria', 'Argungu', null);
insert into countries (name, city, state) values ('France', 'Bondoufle', 'Île-de-France');
insert into countries (name, city, state) values ('Cuba', 'Sagua la Grande', null);
insert into countries (name, city, state) values ('Mexico', 'Ricardo Flores Magon', 'Veracruz Llave');
insert into countries (name, city, state) values ('United States', 'Washington', 'District of Columbia');
insert into countries (name, city, state) values ('Honduras', 'Azacualpa', null);
insert into countries (name, city, state) values ('Greece', 'Mílos', null);
insert into countries (name, city, state) values ('Ireland', 'Enniskerry', null);
insert into countries (name, city, state) values ('Brazil', 'Santa Gertrudes', null);
insert into countries (name, city, state) values ('Russia', 'Nogliki', null);
insert into countries (name, city, state) values ('Philippines', 'Saguday', null);
insert into countries (name, city, state) values ('Sweden', 'Mölnlycke', 'Västra Götaland');
insert into countries (name, city, state) values ('Indonesia', 'Jajaway', null);
insert into countries (name, city, state) values ('Brazil', 'Santo André', null);
insert into countries (name, city, state) values ('China', 'Dabaozi', null);
insert into countries (name, city, state) values ('Ireland', 'Tuam', null);
insert into countries (name, city, state) values ('China', 'Zhangjiawo', null);
insert into countries (name, city, state) values ('Syria', 'Darkūsh', null);
insert into countries (name, city, state) values ('Spain', 'Madrid', 'Madrid');
insert into countries (name, city, state) values ('China', 'Luzhou', null);
insert into countries (name, city, state) values ('Indonesia', 'Lembur Tengah', null);
insert into countries (name, city, state) values ('Portugal', 'Carvalho', 'Porto');
insert into countries (name, city, state) values ('China', 'Baipu', null);
insert into countries (name, city, state) values ('Syria', 'كاف الجاع', null);
insert into countries (name, city, state) values ('Japan', 'Muramatsu', null);
insert into countries (name, city, state) values ('China', 'Xiexiong', null);
insert into countries (name, city, state) values ('China', 'Huizhai', null);
insert into countries (name, city, state) values ('Brazil', 'Brasília de Minas', null);
insert into countries (name, city, state) values ('Indonesia', 'Margamukti', null);
insert into countries (name, city, state) values ('China', 'Longfengshan', null);
insert into countries (name, city, state) values ('China', 'Bajia', null);
insert into countries (name, city, state) values ('Indonesia', 'Dalam', null);
insert into countries (name, city, state) values ('Philippines', 'Caridad', null);
insert into countries (name, city, state) values ('Brazil', 'Mangaratiba', null);
insert into countries (name, city, state) values ('Portugal', 'Fiães', 'Aveiro');
insert into countries (name, city, state) values ('China', 'Tianxin', null);
insert into countries (name, city, state) values ('Czech Republic', 'Železná Ruda', null);
insert into countries (name, city, state) values ('Greenland', 'Aasiaat', null);
insert into countries (name, city, state) values ('France', 'Paris 02', 'Île-de-France');
insert into countries (name, city, state) values ('Poland', 'Miłosław', null);
insert into countries (name, city, state) values ('Russia', 'Kazan', null);
insert into countries (name, city, state) values ('Vietnam', 'Long Hồ', null);
insert into countries (name, city, state) values ('Indonesia', 'Kedatuan', null);
insert into countries (name, city, state) values ('United States', 'Wilmington', 'Delaware');
insert into countries (name, city, state) values ('Greece', 'Nigríta', null);
insert into countries (name, city, state) values ('China', 'Jiaqiao', null);
insert into countries (name, city, state) values ('China', 'Jiaoqiao', null);
insert into countries (name, city, state) values ('Sweden', 'Huddinge', 'Stockholm');
insert into countries (name, city, state) values ('Philippines', 'Agdangan', null);
insert into countries (name, city, state) values ('Indonesia', 'Manalu', null);
insert into countries (name, city, state) values ('China', 'Quanshang', null);
insert into countries (name, city, state) values ('Botswana', 'Janeng', null);
insert into countries (name, city, state) values ('China', 'Jiwei', null);
insert into countries (name, city, state) values ('Russia', 'Kovylkino', null);
insert into countries (name, city, state) values ('Czech Republic', 'Velký Týnec', null);
insert into countries (name, city, state) values ('South Korea', 'Andong', null);
insert into countries (name, city, state) values ('Latvia', 'Kocēni', null);
insert into countries (name, city, state) values ('Philippines', 'Baguio', null);
insert into countries (name, city, state) values ('China', 'Lantian', null);
insert into countries (name, city, state) values ('Vietnam', 'Tây Ninh', null);
insert into countries (name, city, state) values ('Russia', 'Novozybkov', null);
insert into countries (name, city, state) values ('United States', 'Portland', 'Oregon');
insert into countries (name, city, state) values ('Indonesia', 'Pora', null);
insert into countries (name, city, state) values ('China', 'Huolongmen', null);
insert into countries (name, city, state) values ('China', 'Dingzigu', null);
insert into countries (name, city, state) values ('China', 'Changchuan', null);
insert into countries (name, city, state) values ('Ethiopia', 'Sebeta', null);
insert into countries (name, city, state) values ('China', 'Jieshou', null);
insert into countries (name, city, state) values ('Mauritius', 'Roches Noire', null);
insert into countries (name, city, state) values ('Japan', 'Haebaru', null);
insert into countries (name, city, state) values ('Finland', 'Hyrynsalmi', null);
insert into countries (name, city, state) values ('Malaysia', 'Kota Kinabalu', 'Sabah');
insert into countries (name, city, state) values ('China', 'Zhitang', null);
insert into countries (name, city, state) values ('Indonesia', 'Negararatu', null);
insert into countries (name, city, state) values ('Philippines', 'Cawayan', null);
insert into countries (name, city, state) values ('Pakistan', 'Khārān', null);
insert into countries (name, city, state) values ('China', 'Shanjiang', null);
insert into countries (name, city, state) values ('Indonesia', 'Maubasa', null);
insert into countries (name, city, state) values ('Russia', 'Velizh', null);
insert into countries (name, city, state) values ('Indonesia', 'Padangtiji', null);
insert into countries (name, city, state) values ('Philippines', 'Mantang', null);
insert into countries (name, city, state) values ('Indonesia', 'Tanjungkerta', null);
insert into countries (name, city, state) values ('Thailand', 'Pakham', null);
insert into countries (name, city, state) values ('Iceland', 'Sandgerði', null);
insert into countries (name, city, state) values ('United States', 'Winston Salem', 'North Carolina');
insert into countries (name, city, state) values ('Brazil', 'Capim Grosso', null);
insert into countries (name, city, state) values ('Peru', 'Conchamarca', null);
insert into countries (name, city, state) values ('Lithuania', 'Kudirkos Naumiestis', null);
insert into countries (name, city, state) values ('China', 'Songgui', null);
insert into countries (name, city, state) values ('China', 'Chayuan', null);
insert into countries (name, city, state) values ('China', 'Xiaozhi', null);
insert into countries (name, city, state) values ('Germany', 'Frankfurt am Main', 'Hessen');
insert into countries (name, city, state) values ('Hungary', 'Dunaújváros', 'Fejér');
insert into countries (name, city, state) values ('Canada', 'Nicolet', 'Québec');
insert into countries (name, city, state) values ('China', 'Mengla', null);
insert into countries (name, city, state) values ('France', 'Bourges', 'Centre');
insert into countries (name, city, state) values ('Russia', 'Siva', null);
insert into countries (name, city, state) values ('Brazil', 'Ubaitaba', null);
insert into countries (name, city, state) values ('Brazil', 'Caldas Novas', null);
insert into countries (name, city, state) values ('France', 'Salon-de-Provence', 'Provence-Alpes-Côte d''Azur');
insert into countries (name, city, state) values ('China', 'Junliangcheng', null);
insert into countries (name, city, state) values ('China', 'Hongqi Yingzi', null);
insert into countries (name, city, state) values ('Philippines', 'Granada', null);
insert into countries (name, city, state) values ('Indonesia', 'Genting', null);
insert into countries (name, city, state) values ('China', 'Xiahong', null);
insert into countries (name, city, state) values ('Bosnia and Herzegovina', 'Vlasenica', null);
insert into countries (name, city, state) values ('United States', 'Boulder', 'Colorado');
insert into countries (name, city, state) values ('Ukraine', 'Starychi', null);
insert into countries (name, city, state) values ('Brazil', 'Santo Antônio de Posse', null);
insert into countries (name, city, state) values ('Macedonia', 'Demir Hisar', null);
insert into countries (name, city, state) values ('Indonesia', 'Karangtengah', null);
insert into countries (name, city, state) values ('Indonesia', 'Pasirbatang', null);
insert into countries (name, city, state) values ('Nepal', 'Bīrganj', null);
insert into countries (name, city, state) values ('Portugal', 'Silvares', 'Castelo Branco');
insert into countries (name, city, state) values ('Poland', 'Wasilków', null);
insert into countries (name, city, state) values ('Sweden', 'Solna', 'Stockholm');
insert into countries (name, city, state) values ('Philippines', 'Unidos', null);
insert into countries (name, city, state) values ('Palestinian Territory', 'Al Judayrah', null);
insert into countries (name, city, state) values ('Myanmar', 'Martaban', null);
insert into countries (name, city, state) values ('Japan', 'Himeji', null);
insert into countries (name, city, state) values ('Russia', 'Psyzh', null);
insert into countries (name, city, state) values ('Portugal', 'Sande São Martinho', 'Braga');
insert into countries (name, city, state) values ('Philippines', 'Bitin', null);
insert into countries (name, city, state) values ('Indonesia', 'Simpang', null);
insert into countries (name, city, state) values ('Canada', 'Harbour Breton', 'Newfoundland and Labrador');
insert into countries (name, city, state) values ('Indonesia', 'Lamongan', null);
insert into countries (name, city, state) values ('Namibia', 'Bagani', null);
insert into countries (name, city, state) values ('Croatia', 'Žrnovo', null);
insert into countries (name, city, state) values ('Indonesia', 'Pandean', null);
insert into countries (name, city, state) values ('Macedonia', 'Shtip', null);
insert into countries (name, city, state) values ('Indonesia', 'Pende', null);
insert into countries (name, city, state) values ('Kenya', 'Kericho', null);
insert into countries (name, city, state) values ('Ghana', 'Savelugu', null);
insert into countries (name, city, state) values ('Brazil', 'Benevides', null);
insert into countries (name, city, state) values ('Russia', 'Kurchatov', null);
insert into countries (name, city, state) values ('China', 'Wanmao', null);
insert into countries (name, city, state) values ('China', 'Fengcheng', null);
insert into countries (name, city, state) values ('Costa Rica', 'San Pedro', null);
insert into countries (name, city, state) values ('Laos', 'Phonsavan', null);
insert into countries (name, city, state) values ('Russia', 'Sapernoye', null);
insert into countries (name, city, state) values ('China', 'Longlou', null);
insert into countries (name, city, state) values ('Sweden', 'Piteå', 'Norrbotten');
insert into countries (name, city, state) values ('China', 'Mingyuedian', null);
insert into countries (name, city, state) values ('Kuwait', 'Salwá', null);
insert into countries (name, city, state) values ('France', 'Fosses', 'Île-de-France');
insert into countries (name, city, state) values ('Czech Republic', 'Hukvaldy', null);
insert into countries (name, city, state) values ('Indonesia', 'Padangan', null);
insert into countries (name, city, state) values ('Ukraine', 'Nikita', null);
insert into countries (name, city, state) values ('Italy', 'Genova', 'Liguria');
insert into countries (name, city, state) values ('Portugal', 'Lamoso', 'Porto');
insert into countries (name, city, state) values ('Peru', 'Honoria', null);
insert into countries (name, city, state) values ('Colombia', 'Facatativá', null);
insert into countries (name, city, state) values ('Afghanistan', 'Ḩukūmat-e Shīnkaī', null);
insert into countries (name, city, state) values ('Peru', 'Mungui', null);
insert into countries (name, city, state) values ('Russia', 'Vatutino', null);
insert into countries (name, city, state) values ('Brazil', 'São João dos Inhamuns', null);
insert into countries (name, city, state) values ('Mexico', 'Hidalgo', 'Chihuahua');
insert into countries (name, city, state) values ('Spain', 'Leon', 'Castilla - Leon');
insert into countries (name, city, state) values ('China', 'Qiaoyi', null);
insert into countries (name, city, state) values ('Czech Republic', 'Vilémov', null);
insert into countries (name, city, state) values ('Indonesia', 'Sapeken', null);
insert into countries (name, city, state) values ('Russia', 'Kolyubakino', null);
insert into countries (name, city, state) values ('Greece', 'Rodolívos', null);
insert into countries (name, city, state) values ('Argentina', 'Marcos Juárez', null);
insert into countries (name, city, state) values ('Indonesia', 'Karangduren Dua', null);
insert into countries (name, city, state) values ('China', 'Tanggan', null);
insert into countries (name, city, state) values ('China', 'Matou', null);
insert into countries (name, city, state) values ('Nigeria', 'Gamawa', null);
insert into countries (name, city, state) values ('Afghanistan', 'Khōshāmand', null);
insert into countries (name, city, state) values ('Albania', 'Shezë', null);
insert into countries (name, city, state) values ('China', 'Dasha', null);
insert into countries (name, city, state) values ('United States', 'Naples', 'Florida');
insert into countries (name, city, state) values ('Russia', 'Vilya', null);
insert into countries (name, city, state) values ('Indonesia', 'Cinangsih Satu', null);
insert into countries (name, city, state) values ('Canada', 'Gibbons', 'Alberta');
insert into countries (name, city, state) values ('Philippines', 'Maulawin', null);
insert into countries (name, city, state) values ('Hungary', 'Nagykanizsa', 'Zala');
insert into countries (name, city, state) values ('Indonesia', 'Cingambul', null);
insert into countries (name, city, state) values ('Mongolia', 'Tsenher', null);
insert into countries (name, city, state) values ('China', 'Guantun', null);
insert into countries (name, city, state) values ('Finland', 'Haapajärvi', null);
insert into countries (name, city, state) values ('United Arab Emirates', 'Ar Ruways', null);
insert into countries (name, city, state) values ('Peru', 'Aricapampa', null);
insert into countries (name, city, state) values ('Luxembourg', 'Bous', null);
insert into countries (name, city, state) values ('South Korea', 'Kwangyang', null);
insert into countries (name, city, state) values ('Philippines', 'Cambanay', null);
insert into countries (name, city, state) values ('China', 'Baoshan', null);
insert into countries (name, city, state) values ('Thailand', 'Ban Phan Don', null);
insert into countries (name, city, state) values ('China', 'Xintai', null);
insert into countries (name, city, state) values ('Brazil', 'Itabaianinha', null);
insert into countries (name, city, state) values ('Indonesia', 'Bagiktinggang', null);
insert into countries (name, city, state) values ('Indonesia', 'Babakantugu', null);
insert into countries (name, city, state) values ('Papua New Guinea', 'Rabaul', null);
insert into countries (name, city, state) values ('Indonesia', 'Nunutba', null);
insert into countries (name, city, state) values ('China', 'Tiehe', null);
insert into countries (name, city, state) values ('Indonesia', 'Mander', null);
insert into countries (name, city, state) values ('China', 'Linghu', null);
insert into countries (name, city, state) values ('Portugal', 'Bairro de Santo António', 'Lisboa');
insert into countries (name, city, state) values ('Pakistan', 'Mehar', null);
insert into countries (name, city, state) values ('Indonesia', 'Kambatatamakawu', null);
insert into countries (name, city, state) values ('Poland', 'Ostrówek', null);
insert into countries (name, city, state) values ('United States', 'Inglewood', 'California');
insert into countries (name, city, state) values ('Libya', 'Giado', null);
insert into countries (name, city, state) values ('Kenya', 'Isiolo', null);
insert into countries (name, city, state) values ('Yemen', 'Al Ma‘allā’', null);
insert into countries (name, city, state) values ('Brazil', 'Itapaci', null);
insert into countries (name, city, state) values ('China', 'Haoshui', null);
insert into countries (name, city, state) values ('Kazakhstan', 'Makīnsk', null);
insert into countries (name, city, state) values ('China', 'Shanlian', null);
insert into countries (name, city, state) values ('Bulgaria', 'Batanovtsi', null);
insert into countries (name, city, state) values ('Palau', 'Kloulklubed', null);
insert into countries (name, city, state) values ('France', 'Pontivy', 'Bretagne');
insert into countries (name, city, state) values ('Egypt', 'Al Bawīţī', null);
insert into countries (name, city, state) values ('Philippines', 'Bato', null);
insert into countries (name, city, state) values ('Thailand', 'Thai Charoen', null);
insert into countries (name, city, state) values ('Poland', 'Nidek', null);
insert into countries (name, city, state) values ('Turkmenistan', 'Yolöten', null);
insert into countries (name, city, state) values ('Poland', 'Witkowo', null);
insert into countries (name, city, state) values ('Indonesia', 'Tulungagung', null);
insert into countries (name, city, state) values ('Mexico', 'San Jose', 'San Luis Potosi');
insert into countries (name, city, state) values ('China', 'Fucheng', null);
insert into countries (name, city, state) values ('France', 'Paris 11', 'Île-de-France');
insert into countries (name, city, state) values ('China', 'Zhangdu', null);
insert into countries (name, city, state) values ('Venezuela', 'Palmasola', null);
insert into countries (name, city, state) values ('China', 'Huangrangping', null);
insert into countries (name, city, state) values ('China', 'Huchang', null);
insert into countries (name, city, state) values ('Peru', 'Maras', null);
insert into countries (name, city, state) values ('China', 'Huya', null);
insert into countries (name, city, state) values ('China', 'Qingxi', null);
insert into countries (name, city, state) values ('Greece', 'Nikísiani', null);
insert into countries (name, city, state) values ('South Africa', 'Krugersdorp', null);
insert into countries (name, city, state) values ('Greece', 'Zákynthos', null);
insert into countries (name, city, state) values ('Peru', 'Lima Pampa', null);
insert into countries (name, city, state) values ('Indonesia', 'Sobang', null);
insert into countries (name, city, state) values ('Russia', 'Yelan’', null);
insert into countries (name, city, state) values ('China', 'Zhongba', null);
insert into countries (name, city, state) values ('Netherlands', 'Arnhem', 'Provincie Gelderland');
insert into countries (name, city, state) values ('Japan', 'Maebashi-shi', null);
insert into countries (name, city, state) values ('Canada', 'Devon', 'Alberta');
insert into countries (name, city, state) values ('Nicaragua', 'Masachapa', null);
insert into countries (name, city, state) values ('China', 'Haimen', null);
insert into countries (name, city, state) values ('China', 'Quanling', null);
insert into countries (name, city, state) values ('Ukraine', 'Svyatogorsk', null);
insert into countries (name, city, state) values ('China', 'Lianglin', null);
insert into countries (name, city, state) values ('Peru', 'Tuti', null);
insert into countries (name, city, state) values ('Egypt', 'Kousa', null);
insert into countries (name, city, state) values ('China', 'Zoushi', null);
insert into countries (name, city, state) values ('Iraq', 'Ad Dujayl', null);
insert into countries (name, city, state) values ('Ukraine', 'Kotsyubyns’ke', null);
insert into countries (name, city, state) values ('Croatia', 'Velika', null);
insert into countries (name, city, state) values ('Indonesia', 'Banjar Pande', null);
insert into countries (name, city, state) values ('Turkmenistan', 'Baharly', null);
insert into countries (name, city, state) values ('China', 'Qutun', null);
insert into countries (name, city, state) values ('China', 'Zhaitou', null);
insert into countries (name, city, state) values ('China', 'Gushan', null);
insert into countries (name, city, state) values ('Pakistan', 'Mehmand Chak', null);
insert into countries (name, city, state) values ('China', 'Fuling', null);
insert into countries (name, city, state) values ('China', 'Liangshuijing', null);
insert into countries (name, city, state) values ('China', 'Datian', null);
insert into countries (name, city, state) values ('Russia', 'Bratsk', null);
insert into countries (name, city, state) values ('Dominican Republic', 'Puerto Plata', null);
insert into countries (name, city, state) values ('Sri Lanka', 'Badulla', null);
insert into countries (name, city, state) values ('Netherlands', 'Rotterdam', 'Provincie Zuid-Holland');
insert into countries (name, city, state) values ('China', 'Neikeng', null);
insert into countries (name, city, state) values ('China', 'Dongtian', null);
insert into countries (name, city, state) values ('China', 'Linglu', null);
insert into countries (name, city, state) values ('Philippines', 'Maria Cristina', null);
insert into countries (name, city, state) values ('China', 'Xinghua', null);
insert into countries (name, city, state) values ('Pakistan', 'Pahārpur', null);
insert into countries (name, city, state) values ('Czech Republic', 'Hodkovičky', null);
insert into countries (name, city, state) values ('Nicaragua', 'Larreynaga', null);
insert into countries (name, city, state) values ('China', 'Samdo', null);
insert into countries (name, city, state) values ('United States', 'Wichita', 'Kansas');
insert into countries (name, city, state) values ('Portugal', 'Passal', 'Viana do Castelo');
insert into countries (name, city, state) values ('Canada', 'Port-Cartier', 'Québec');
insert into countries (name, city, state) values ('China', 'Tangcun', null);
insert into countries (name, city, state) values ('Indonesia', 'Pondoktelo', null);
insert into countries (name, city, state) values ('Peru', 'Tirapata', null);
insert into countries (name, city, state) values ('Honduras', 'Morocelí', null);
insert into countries (name, city, state) values ('France', 'Alès', 'Languedoc-Roussillon');
insert into countries (name, city, state) values ('Philippines', 'Zumarraga', null);
insert into countries (name, city, state) values ('Cuba', 'Aguada de Pasajeros', null);
insert into countries (name, city, state) values ('Poland', 'Sulechów', null);
insert into countries (name, city, state) values ('Portugal', 'Santa Cruz das Flores', 'Ilha das Flores');
insert into countries (name, city, state) values ('Brazil', 'Imperatriz', null);
insert into countries (name, city, state) values ('Sweden', 'Västra Frölunda', 'Västra Götaland');
insert into countries (name, city, state) values ('Poland', 'Mrągowo', null);
insert into countries (name, city, state) values ('Azerbaijan', 'Hacıqabul', null);
insert into countries (name, city, state) values ('China', 'Xianshuigu', null);
insert into countries (name, city, state) values ('Cambodia', 'Koh Kong', null);
insert into countries (name, city, state) values ('China', 'Fengmen', null);
insert into countries (name, city, state) values ('Philippines', 'Aurora', null);
insert into countries (name, city, state) values ('China', 'Jinkou', null);
insert into countries (name, city, state) values ('Uganda', 'Margherita', null);
insert into countries (name, city, state) values ('China', 'Caotan', null);
insert into countries (name, city, state) values ('Brazil', 'São Luís do Quitunde', null);
insert into countries (name, city, state) values ('Dominican Republic', 'Hato Mayor del Rey', null);
insert into countries (name, city, state) values ('Philippines', 'Tariji', null);
insert into countries (name, city, state) values ('Indonesia', 'Ladan', null);
insert into countries (name, city, state) values ('China', 'Yujing', null);
insert into countries (name, city, state) values ('Jordan', 'Adir', null);
insert into countries (name, city, state) values ('Brazil', 'Timbó', null);
insert into countries (name, city, state) values ('China', 'Gaotang', null);
insert into countries (name, city, state) values ('Russia', 'Talitsy', null);
insert into countries (name, city, state) values ('Indonesia', 'Bintang', null);
insert into countries (name, city, state) values ('Philippines', 'Lapuyan', null);
insert into countries (name, city, state) values ('Canada', 'Houston', 'British Columbia');
insert into countries (name, city, state) values ('Honduras', 'San Jerónimo', null);
insert into countries (name, city, state) values ('Ukraine', 'Stari Kuty', null);
insert into countries (name, city, state) values ('Russia', 'Verkhniy Baskunchak', null);
insert into countries (name, city, state) values ('China', 'Huangdimiao', null);
insert into countries (name, city, state) values ('Japan', 'Tokoname', null);
insert into countries (name, city, state) values ('Malaysia', 'Kota Kinabalu', 'Sabah');
insert into countries (name, city, state) values ('Russia', 'Chernukha', null);
insert into countries (name, city, state) values ('China', 'Baota', null);
insert into countries (name, city, state) values ('Malawi', 'Luchenza', null);
insert into countries (name, city, state) values ('Russia', 'Yakutsk', null);
insert into countries (name, city, state) values ('Brazil', 'Quatá', null);
insert into countries (name, city, state) values ('China', 'Aoluguya Ewenke Minzu', null);
insert into countries (name, city, state) values ('Russia', 'Bessonovka', null);
insert into countries (name, city, state) values ('China', 'Baitouli', null);
insert into countries (name, city, state) values ('Indonesia', 'Ndewel', null);
insert into countries (name, city, state) values ('Pakistan', 'Khuzdār', null);
insert into countries (name, city, state) values ('Indonesia', 'Ngujuran', null);
insert into countries (name, city, state) values ('China', 'Shouchun', null);
insert into countries (name, city, state) values ('Brazil', 'Artur Nogueira', null);
insert into countries (name, city, state) values ('Philippines', 'Bunog', null);
insert into countries (name, city, state) values ('Laos', 'Muang Long', null);
insert into countries (name, city, state) values ('Indonesia', 'Krajansumbermujur', null);
insert into countries (name, city, state) values ('India', 'R S', 'Gujarat');
insert into countries (name, city, state) values ('Indonesia', 'Dajalorong', null);
insert into countries (name, city, state) values ('Paraguay', 'Itauguá', null);
insert into countries (name, city, state) values ('Indonesia', 'Nao', null);
insert into countries (name, city, state) values ('China', 'Beitan', null);
insert into countries (name, city, state) values ('Japan', 'Ayabe', null);
insert into countries (name, city, state) values ('China', 'Runsonglaozhai', null);
insert into countries (name, city, state) values ('Philippines', 'Looc', null);
insert into countries (name, city, state) values ('Indonesia', 'Penebel', null);
insert into countries (name, city, state) values ('Indonesia', 'Botoh', null);
insert into countries (name, city, state) values ('China', 'Moxi', null);
insert into countries (name, city, state) values ('Venezuela', 'El Dividive', null);
insert into countries (name, city, state) values ('China', 'Baikui', null);
insert into countries (name, city, state) values ('Peru', 'Chalaco', null);
insert into countries (name, city, state) values ('Indonesia', 'Pisang', null);
insert into countries (name, city, state) values ('Ukraine', 'Rybache', null);
insert into countries (name, city, state) values ('Sweden', 'Forshaga', 'Värmland');
insert into countries (name, city, state) values ('Guinea-Bissau', 'Cacheu', null);
insert into countries (name, city, state) values ('China', 'Zengjia', null);
insert into countries (name, city, state) values ('China', 'Tianhe', null);
insert into countries (name, city, state) values ('China', 'Zhanjia', null);
insert into countries (name, city, state) values ('Indonesia', 'Bagangan', null);
insert into countries (name, city, state) values ('China', 'Haizigou', null);
insert into countries (name, city, state) values ('Vietnam', 'Phú Mỹ', null);
insert into countries (name, city, state) values ('Philippines', 'Kagawasan', null);
insert into countries (name, city, state) values ('Indonesia', 'Kuala Bhee', null);
insert into countries (name, city, state) values ('Honduras', 'Morocelí', null);
insert into countries (name, city, state) values ('Paraguay', 'Ciudad del Este', null);
insert into countries (name, city, state) values ('Vietnam', 'Bắc Ninh', null);
insert into countries (name, city, state) values ('Czech Republic', 'Chropyně', null);
insert into countries (name, city, state) values ('Saudi Arabia', 'Al Jarādīyah', null);
insert into countries (name, city, state) values ('Philippines', 'Buliran', null);
insert into countries (name, city, state) values ('China', 'Danxi', null);
insert into countries (name, city, state) values ('Sweden', 'Falun', 'Dalarna');
insert into countries (name, city, state) values ('Canada', 'Côte-Saint-Luc', 'Québec');
insert into countries (name, city, state) values ('China', 'Yangdu', null);
insert into countries (name, city, state) values ('Ukraine', 'Brusyliv', null);
insert into countries (name, city, state) values ('Vietnam', 'Tân Việt', null);
insert into countries (name, city, state) values ('Sweden', 'Falun', 'Dalarna');
insert into countries (name, city, state) values ('Indonesia', 'Sepanjang', null);
insert into countries (name, city, state) values ('France', 'Thiais', 'Île-de-France');
insert into countries (name, city, state) values ('Indonesia', 'Rawuk', null);
insert into countries (name, city, state) values ('Poland', 'Chorkówka', null);
insert into countries (name, city, state) values ('Philippines', 'San Ramon', null);
insert into countries (name, city, state) values ('China', 'Buchou', null);
insert into countries (name, city, state) values ('France', 'Marseille', 'Provence-Alpes-Côte d''Azur');
insert into countries (name, city, state) values ('Indonesia', 'Kebonsari Kidul', null);
insert into countries (name, city, state) values ('Russia', 'Podkumskiy', null);
insert into countries (name, city, state) values ('Poland', 'Borzęcin', null);
insert into countries (name, city, state) values ('Ukraine', 'Korsun’-Shevchenkivs’kyy', null);
insert into countries (name, city, state) values ('Indonesia', 'Pasrukrajan Satu', null);
insert into countries (name, city, state) values ('Portugal', 'Sever do Vouga', 'Aveiro');
insert into countries (name, city, state) values ('China', 'Baisha', null);
insert into countries (name, city, state) values ('Gambia', 'Pateh Sam', null);
insert into countries (name, city, state) values ('Thailand', 'Sawankhalok', null);
insert into countries (name, city, state) values ('China', 'Jinbo', null);
insert into countries (name, city, state) values ('Indonesia', 'Ponggeok', null);
insert into countries (name, city, state) values ('Indonesia', 'Magepanda', null);
insert into countries (name, city, state) values ('Angola', 'Luena', null);
insert into countries (name, city, state) values ('Brazil', 'Quixeramobim', null);
insert into countries (name, city, state) values ('Sweden', 'Älvdalen', 'Dalarna');
insert into countries (name, city, state) values ('Slovenia', 'Moravče', null);
insert into countries (name, city, state) values ('United States', 'Alexandria', 'Louisiana');
insert into countries (name, city, state) values ('Indonesia', 'Batibati', null);
insert into countries (name, city, state) values ('China', 'Xinji', null);
insert into countries (name, city, state) values ('Indonesia', 'Umbanyar', null);
insert into countries (name, city, state) values ('Finland', 'Hausjärvi', null);
insert into countries (name, city, state) values ('China', 'Wuguishan', null);
insert into countries (name, city, state) values ('Syria', 'Al Mushannaf', null);
insert into countries (name, city, state) values ('Ukraine', 'Osypenko', null);
insert into countries (name, city, state) values ('Ukraine', 'Shyroke', null);
insert into countries (name, city, state) values ('Panama', 'Dolega District', null);
insert into countries (name, city, state) values ('Indonesia', 'Sepanjang', null);
insert into countries (name, city, state) values ('Angola', 'N’dalatando', null);
insert into countries (name, city, state) values ('France', 'Villeurbanne', 'Rhône-Alpes');
insert into countries (name, city, state) values ('Russia', 'Plavsk', null);
insert into countries (name, city, state) values ('Indonesia', 'Tanggeung Kolot', null);
insert into countries (name, city, state) values ('Sweden', 'Dorotea', 'Västerbotten');
insert into countries (name, city, state) values ('Egypt', 'Banhā', null);
insert into countries (name, city, state) values ('Ethiopia', 'Tippi', null);
insert into countries (name, city, state) values ('China', 'Xijiao', null);
insert into countries (name, city, state) values ('Bahamas', 'San Andros', null);
insert into countries (name, city, state) values ('France', 'Mulhouse', 'Alsace');
insert into countries (name, city, state) values ('Indonesia', 'Jawa', null);
insert into countries (name, city, state) values ('Azerbaijan', 'Amirdzhan', null);
insert into countries (name, city, state) values ('Yemen', 'Najd al Jumā‘ī', null);
insert into countries (name, city, state) values ('Cameroon', 'Bafoussam', null);
insert into countries (name, city, state) values ('Syria', 'Sinjār', null);
insert into countries (name, city, state) values ('China', 'Shangyong', null);
insert into countries (name, city, state) values ('Indonesia', 'Timba Lauk', null);
insert into countries (name, city, state) values ('Japan', 'Tsushima', null);
insert into countries (name, city, state) values ('United States', 'Louisville', 'Kentucky');
insert into countries (name, city, state) values ('Germany', 'Köln', 'Nordrhein-Westfalen');
insert into countries (name, city, state) values ('Chile', 'Coronel', null);
insert into countries (name, city, state) values ('Indonesia', 'Krajan Dua Padomasan', null);
insert into countries (name, city, state) values ('Denmark', 'København', 'Region Hovedstaden');
insert into countries (name, city, state) values ('Botswana', 'Janeng', null);
insert into countries (name, city, state) values ('Portugal', 'Santa Cruz', 'Braga');
insert into countries (name, city, state) values ('China', 'Quanyang', null);
insert into countries (name, city, state) values ('Niger', 'Mirriah', null);
insert into countries (name, city, state) values ('Peru', 'Usquil', null);
insert into countries (name, city, state) values ('Estonia', 'Tallinn', null);
insert into countries (name, city, state) values ('French Polynesia', 'Arue', null);
insert into countries (name, city, state) values ('Mexico', 'Solidaridad', 'Tamaulipas');
insert into countries (name, city, state) values ('Afghanistan', '’Unābah', null);
insert into countries (name, city, state) values ('China', 'Danan', null);
insert into countries (name, city, state) values ('Japan', 'Minokamo', null);
insert into countries (name, city, state) values ('China', 'Heping', null);
insert into countries (name, city, state) values ('China', 'Dongling', null);
insert into countries (name, city, state) values ('Sweden', 'Vellinge', 'Skåne');
insert into countries (name, city, state) values ('Japan', 'Fukuchiyama', null);
insert into countries (name, city, state) values ('Nigeria', 'Ogurugu', null);
insert into countries (name, city, state) values ('Canada', 'Shediac', 'New Brunswick');
insert into countries (name, city, state) values ('Philippines', 'Songculan', null);
insert into countries (name, city, state) values ('Madagascar', 'Ambalavao', null);
insert into countries (name, city, state) values ('Brazil', 'Japeri', null);
insert into countries (name, city, state) values ('Vietnam', 'Nhà Bàng', null);
insert into countries (name, city, state) values ('Sweden', 'Köping', 'Västmanland');
insert into countries (name, city, state) values ('Bosnia and Herzegovina', 'Bosanski Novi', null);
insert into countries (name, city, state) values ('Morocco', 'Bhalil', null);
insert into countries (name, city, state) values ('China', 'Haodian', null);
insert into countries (name, city, state) values ('Indonesia', 'Sumberarumkrajan', null);
insert into countries (name, city, state) values ('Indonesia', 'Tambakrejo', null);
insert into countries (name, city, state) values ('Indonesia', 'Krajan Dukuhseti', null);
insert into countries (name, city, state) values ('Poland', 'Sidzina', null);
insert into countries (name, city, state) values ('Jordan', '‘Izrā', null);
insert into countries (name, city, state) values ('China', 'Beiguoyuan', null);
insert into countries (name, city, state) values ('Argentina', 'La Clotilde', null);
insert into countries (name, city, state) values ('Philippines', 'Cabannungan Second', null);
insert into countries (name, city, state) values ('China', 'Damu', null);
insert into countries (name, city, state) values ('Ukraine', 'Novyy Svit', null);
insert into countries (name, city, state) values ('Russia', 'Zhatay', null);
insert into countries (name, city, state) values ('Morocco', 'Goulmima', null);
insert into countries (name, city, state) values ('Uruguay', 'Florencio Sánchez', null);
insert into countries (name, city, state) values ('Mexico', 'San Antonio', 'Hidalgo');
insert into countries (name, city, state) values ('Portugal', 'Trinaterra', 'Porto');
insert into countries (name, city, state) values ('Greece', 'Kastélli', null);
insert into countries (name, city, state) values ('Indonesia', 'Lengkong', null);
insert into countries (name, city, state) values ('China', 'Zhaowu', null);
insert into countries (name, city, state) values ('Ukraine', 'Kolodenka', null);
insert into countries (name, city, state) values ('Bulgaria', 'Troyan', null);
insert into countries (name, city, state) values ('Peru', 'Cachimayo', null);
insert into countries (name, city, state) values ('Norway', 'Trondheim', 'Sor-Trondelag');
insert into countries (name, city, state) values ('Sweden', 'Gävle', 'Gävleborg');
insert into countries (name, city, state) values ('Armenia', 'Drakhtik', null);
insert into countries (name, city, state) values ('Mexico', 'Lindavista', 'Guanajuato');
insert into countries (name, city, state) values ('Indonesia', 'Keputran', null);
insert into countries (name, city, state) values ('Poland', 'Babica', null);
insert into countries (name, city, state) values ('Comoros', 'Mirontsi', null);
insert into countries (name, city, state) values ('Indonesia', 'Medalem', null);
insert into countries (name, city, state) values ('Peru', 'Canchaque', null);
insert into countries (name, city, state) values ('Ecuador', 'Cayambe', null);
insert into countries (name, city, state) values ('East Timor', 'Lospalos', null);
insert into countries (name, city, state) values ('China', 'Rulong', null);
insert into countries (name, city, state) values ('Czech Republic', 'Loučná nad Desnou', null);
insert into countries (name, city, state) values ('Brazil', 'Murici', null);
insert into countries (name, city, state) values ('China', 'Panjiang', null);
insert into countries (name, city, state) values ('Philippines', 'Ransang', null);
insert into countries (name, city, state) values ('France', 'Aix-les-Bains', 'Rhône-Alpes');
insert into countries (name, city, state) values ('North Korea', 'Kapsan-ŭp', null);
insert into countries (name, city, state) values ('Saint Lucia', 'Micoud', null);
insert into countries (name, city, state) values ('Honduras', 'El Porvenir', null);
insert into countries (name, city, state) values ('Ireland', 'Monaghan', null);
insert into countries (name, city, state) values ('Iceland', 'Vogar', null);
insert into countries (name, city, state) values ('Indonesia', 'Awilega', null);
insert into countries (name, city, state) values ('Vanuatu', 'Port-Vila', null);
insert into countries (name, city, state) values ('Portugal', 'Lage', 'Viana do Castelo');
insert into countries (name, city, state) values ('Philippines', 'Patong', null);
insert into countries (name, city, state) values ('China', 'Dadoupu', null);
insert into countries (name, city, state) values ('Vietnam', 'Khe Tre', null);
insert into countries (name, city, state) values ('Canada', 'Two Hills', 'Alberta');
insert into countries (name, city, state) values ('Indonesia', 'Pajaten', null);
insert into countries (name, city, state) values ('Pakistan', 'Baffa', null);
insert into countries (name, city, state) values ('Japan', 'Shizukuishi', null);
insert into countries (name, city, state) values ('Indonesia', 'Modosinal', null);
insert into countries (name, city, state) values ('Philippines', 'Cavinti', null);
insert into countries (name, city, state) values ('Indonesia', 'Kalisari', null);
insert into countries (name, city, state) values ('Russia', 'Severobaykal’sk', null);
insert into countries (name, city, state) values ('Sweden', 'Trollhättan', 'Västra Götaland');
insert into countries (name, city, state) values ('Brazil', 'Blumenau', null);
insert into countries (name, city, state) values ('China', 'Qinhong', null);
insert into countries (name, city, state) values ('Indonesia', 'Mulyo', null);
insert into countries (name, city, state) values ('Ecuador', 'Jipijapa', null);
insert into countries (name, city, state) values ('Philippines', 'Cordova', null);
insert into countries (name, city, state) values ('Philippines', 'Kawit', null);
insert into countries (name, city, state) values ('Malaysia', 'Melaka', 'Melaka');
insert into countries (name, city, state) values ('Niger', 'Téra', null);
insert into countries (name, city, state) values ('France', 'Meylan', 'Rhône-Alpes');
insert into countries (name, city, state) values ('Ireland', 'Valleymount', null);
insert into countries (name, city, state) values ('Indonesia', 'Glagahdowo', null);
insert into countries (name, city, state) values ('Bulgaria', 'Novo Selo', null);
insert into countries (name, city, state) values ('Argentina', 'Tres Arroyos', null);
insert into countries (name, city, state) values ('Greece', 'Árta', null);
insert into countries (name, city, state) values ('Indonesia', 'Oematnunu', null);
insert into countries (name, city, state) values ('China', 'Zhenjiang', null);
insert into countries (name, city, state) values ('Afghanistan', 'Ghurayd Gharamē', null);
insert into countries (name, city, state) values ('China', 'Luoshan', null);
insert into countries (name, city, state) values ('China', 'Leiguan', null);
insert into countries (name, city, state) values ('Japan', 'Miki', null);
insert into countries (name, city, state) values ('Nigeria', 'Owerri', null);
insert into countries (name, city, state) values ('Democratic Republic of the Congo', 'Bondo', null);
insert into countries (name, city, state) values ('Colombia', 'Carmen de Viboral', null);
insert into countries (name, city, state) values ('Zimbabwe', 'Esigodini', null);
insert into countries (name, city, state) values ('China', 'Guozhen', null);
insert into countries (name, city, state) values ('China', 'Zoumachang', null);
insert into countries (name, city, state) values ('China', 'Nandong', null);
insert into countries (name, city, state) values ('Philippines', 'Carmen', null);
insert into countries (name, city, state) values ('Indonesia', 'Masu', null);
insert into countries (name, city, state) values ('United States', 'New Orleans', 'Louisiana');
insert into countries (name, city, state) values ('China', 'Gaoqiao', null);
insert into countries (name, city, state) values ('Panama', 'Paraíso', null);
insert into countries (name, city, state) values ('Afghanistan', 'Quchanghī', null);
insert into countries (name, city, state) values ('China', 'Jialou', null);
insert into countries (name, city, state) values ('Russia', 'Petrokamenskoye', null);
insert into countries (name, city, state) values ('Poland', 'Markowa', null);
insert into countries (name, city, state) values ('Russia', 'Siverskiy', null);
insert into countries (name, city, state) values ('Brazil', 'Timon', null);
insert into countries (name, city, state) values ('Poland', 'Sulmierzyce', null);
insert into countries (name, city, state) values ('China', 'Duobaoshan', null);
insert into countries (name, city, state) values ('Palestinian Territory', 'Ad Dawḩah', null);
insert into countries (name, city, state) values ('Italy', 'Genova', 'Liguria');
insert into countries (name, city, state) values ('Ukraine', 'Kochetok', null);
insert into countries (name, city, state) values ('China', 'Gulong', null);
insert into countries (name, city, state) values ('Argentina', 'Zárate', null);
insert into countries (name, city, state) values ('Poland', 'Łodygowice', null);
insert into countries (name, city, state) values ('Uganda', 'Kaabong', null);
insert into countries (name, city, state) values ('Japan', 'Miyoshi', null);
insert into countries (name, city, state) values ('Afghanistan', 'Pārūn', null);
insert into countries (name, city, state) values ('Indonesia', 'Riung', null);
insert into countries (name, city, state) values ('Panama', 'San Andrés', null);
insert into countries (name, city, state) values ('Afghanistan', 'Ḩāfiz̧ Moghul', null);
insert into countries (name, city, state) values ('Japan', 'Sukumo', null);
insert into countries (name, city, state) values ('Russia', 'Kronshtadt', null);
insert into countries (name, city, state) values ('Yemen', 'Qishn', null);
insert into countries (name, city, state) values ('Greece', 'Chrysoúpolis', null);
insert into countries (name, city, state) values ('Saint Vincent and the Grenadines', 'Barrouallie', null);
insert into countries (name, city, state) values ('Honduras', 'Casa Quemada', null);
insert into countries (name, city, state) values ('Portugal', 'Cotovia', 'Setúbal');
insert into countries (name, city, state) values ('Indonesia', 'Awilega', null);
insert into countries (name, city, state) values ('China', 'Sanxing', null);
insert into countries (name, city, state) values ('Finland', 'Lumijoki', null);
insert into countries (name, city, state) values ('Sri Lanka', 'Mulleriyawa', null);
insert into countries (name, city, state) values ('China', 'Shicong', null);
insert into countries (name, city, state) values ('Indonesia', 'Kostarea Satu', null);
insert into countries (name, city, state) values ('Kosovo', 'Zubin Potok', null);
insert into countries (name, city, state) values ('Angola', 'Huambo', null);
insert into countries (name, city, state) values ('Sweden', 'Östersund', 'Jämtland');
insert into countries (name, city, state) values ('Philippines', 'Santa Monica', null);
insert into countries (name, city, state) values ('China', 'Jingu', null);
insert into countries (name, city, state) values ('Colombia', 'Onzaga', null);
insert into countries (name, city, state) values ('Czech Republic', 'Ratíškovice', null);
insert into countries (name, city, state) values ('Russia', 'Nizhnyaya Tura', null);
insert into countries (name, city, state) values ('Syria', 'Sirghāyā', null);
insert into countries (name, city, state) values ('Czech Republic', 'Liběšice', null);
insert into countries (name, city, state) values ('Indonesia', 'Pahonjean', null);
insert into countries (name, city, state) values ('China', 'Taihu', null);
insert into countries (name, city, state) values ('China', 'Shiban', null);
insert into countries (name, city, state) values ('Brazil', 'Trindade', null);
insert into countries (name, city, state) values ('Peru', 'Pillpinto', null);
insert into countries (name, city, state) values ('China', 'Zhangqing', null);
insert into countries (name, city, state) values ('Guinea', 'Kissidougou', null);
insert into countries (name, city, state) values ('Syria', 'Ar Ruḩaybah', null);
insert into countries (name, city, state) values ('Jamaica', 'Ulster Spring', null);
insert into countries (name, city, state) values ('Greece', 'Livádion', null);
insert into countries (name, city, state) values ('Thailand', 'Tha Luang', null);
insert into countries (name, city, state) values ('China', 'Jinhe', null);
insert into countries (name, city, state) values ('Indonesia', 'Tajur', null);
insert into countries (name, city, state) values ('Finland', 'Asikkala', null);
insert into countries (name, city, state) values ('Indonesia', 'Sidomulyo', null);
insert into countries (name, city, state) values ('Russia', 'Yakovlevskoye', null);
insert into countries (name, city, state) values ('France', 'Agen', 'Aquitaine');
insert into countries (name, city, state) values ('Indonesia', 'Rengasdengklok', null);
insert into countries (name, city, state) values ('Poland', 'Grodków', null);
insert into countries (name, city, state) values ('Poland', 'Kolbuszowa', null);
insert into countries (name, city, state) values ('Czech Republic', 'Telnice', null);
insert into countries (name, city, state) values ('Belgium', 'Charleroi', 'Wallonie');
insert into countries (name, city, state) values ('Sierra Leone', 'Mobai', null);
insert into countries (name, city, state) values ('Brazil', 'São Paulo', null);
insert into countries (name, city, state) values ('China', 'Guojiaba', null);
insert into countries (name, city, state) values ('Brazil', 'Nortelândia', null);
insert into countries (name, city, state) values ('New Caledonia', 'Fayaoué', null);
insert into countries (name, city, state) values ('France', 'Paris 09', 'Île-de-France');
insert into countries (name, city, state) values ('Vietnam', 'Thị Trấn Than Uyên', null);
insert into countries (name, city, state) values ('Thailand', 'Kalasin', null);
insert into countries (name, city, state) values ('Nigeria', 'Ubiaja', null);
insert into countries (name, city, state) values ('China', 'Niutian', null);
insert into countries (name, city, state) values ('Guatemala', 'Sacapulas', null);
insert into countries (name, city, state) values ('China', 'Gangnan', null);
insert into countries (name, city, state) values ('Peru', 'Huanipaca', null);
insert into countries (name, city, state) values ('Czech Republic', 'Dolní Sloupnice', null);
insert into countries (name, city, state) values ('Cuba', 'Moa', null);
insert into countries (name, city, state) values ('Egypt', 'Qaşr al Farāfirah', null);
insert into countries (name, city, state) values ('Russia', 'Krasnyye Barrikady', null);
insert into countries (name, city, state) values ('Philippines', 'Camp Flora', null);
insert into countries (name, city, state) values ('Poland', 'Twardogóra', null);
insert into countries (name, city, state) values ('China', 'Linxi', null);
insert into countries (name, city, state) values ('Argentina', 'Colonia Aurora', null);
insert into countries (name, city, state) values ('Indonesia', 'Srabah', null);
insert into countries (name, city, state) values ('Peru', 'Cayna', null);
insert into countries (name, city, state) values ('Uzbekistan', 'Qorao’zak', null);
insert into countries (name, city, state) values ('Indonesia', 'Sukasari', null);
insert into countries (name, city, state) values ('Portugal', 'Alvega', 'Santarém');
insert into countries (name, city, state) values ('China', 'Sanshilipu', null);
insert into countries (name, city, state) values ('China', 'Nanzhen', null);
insert into countries (name, city, state) values ('France', 'Caen', 'Basse-Normandie');
insert into countries (name, city, state) values ('Philippines', 'Del Rosario', null);
insert into countries (name, city, state) values ('South Africa', 'Impendle', null);
insert into countries (name, city, state) values ('Ukraine', 'Novovorontsovka', null);
insert into countries (name, city, state) values ('New Caledonia', 'Ouégoa', null);
insert into countries (name, city, state) values ('Thailand', 'Si Satchanalai', null);
insert into countries (name, city, state) values ('Indonesia', 'Jeding', null);
insert into countries (name, city, state) values ('China', 'Tiepu', null);
insert into countries (name, city, state) values ('France', 'Paris 09', 'Île-de-France');
insert into countries (name, city, state) values ('Canada', 'Pictou', 'Nova Scotia');
insert into countries (name, city, state) values ('Ukraine', 'Vinnytsya', null);
insert into countries (name, city, state) values ('Russia', 'Novoanninskiy', null);
insert into countries (name, city, state) values ('China', 'Jianqiao', null);
insert into countries (name, city, state) values ('China', 'Dengzhuang', null);
insert into countries (name, city, state) values ('Indonesia', 'Pakapasan Girang', null);
insert into countries (name, city, state) values ('France', 'Saint-Lô', 'Basse-Normandie');
insert into countries (name, city, state) values ('Philippines', 'Nama', null);
insert into countries (name, city, state) values ('Peru', 'Pimentel', null);
insert into countries (name, city, state) values ('China', 'Dagar', null);
insert into countries (name, city, state) values ('China', 'Gaotai', null);
insert into countries (name, city, state) values ('Poland', 'Lipinki Łużyckie', null);
insert into countries (name, city, state) values ('Russia', 'Kobrinskoye', null);
insert into countries (name, city, state) values ('Canada', 'Kerrobert', 'Saskatchewan');
insert into countries (name, city, state) values ('South Korea', 'Kwangmyŏng', null);
insert into countries (name, city, state) values ('China', 'Xuji', null);
insert into countries (name, city, state) values ('Cameroon', 'Guider', null);
insert into countries (name, city, state) values ('China', 'Xinqiao', null);
insert into countries (name, city, state) values ('Argentina', 'Ordóñez', null);
insert into countries (name, city, state) values ('Thailand', 'Bang Racham', null);
insert into countries (name, city, state) values ('South Africa', 'Lydenburg', null);
insert into countries (name, city, state) values ('Poland', 'Ciechocin', null);
insert into countries (name, city, state) values ('China', 'Yunhe', null);
insert into countries (name, city, state) values ('Afghanistan', 'Markaz-e Ḩukūmat-e Darwēshān', null);
insert into countries (name, city, state) values ('Greece', 'Mégara', null);
insert into countries (name, city, state) values ('Brazil', 'Augusto Corrêa', null);
insert into countries (name, city, state) values ('Philippines', 'Bugo', null);
insert into countries (name, city, state) values ('China', 'Guohe', null);
insert into countries (name, city, state) values ('Japan', 'Enzan', null);
insert into countries (name, city, state) values ('France', 'Le Blanc-Mesnil', 'Île-de-France');
insert into countries (name, city, state) values ('Brazil', 'Guaíba', null);
insert into countries (name, city, state) values ('Kenya', 'Kapsabet', null);
insert into countries (name, city, state) values ('Argentina', 'San Pedro', null);
insert into countries (name, city, state) values ('Greece', 'Káto Dhiminió', null);
insert into countries (name, city, state) values ('Thailand', 'Pluak Daeng', null);
insert into countries (name, city, state) values ('Netherlands', 'Emmen', 'Provincie Drenthe');
insert into countries (name, city, state) values ('France', 'Langres', 'Champagne-Ardenne');
insert into countries (name, city, state) values ('Czech Republic', 'Štěnovice', null);
insert into countries (name, city, state) values ('Guatemala', 'Pajapita', null);
insert into countries (name, city, state) values ('Ukraine', 'Rozhniv', null);
insert into countries (name, city, state) values ('Canada', 'La Sarre', 'Québec');
insert into countries (name, city, state) values ('France', 'Blagnac', 'Midi-Pyrénées');
insert into countries (name, city, state) values ('Brazil', 'Abaeté', null);
insert into countries (name, city, state) values ('Portugal', 'Além', 'Braga');
