insert into items (name, price, offer) values ('Lid Tray - 16in Dome', 50.44, 2.87);
insert into items (name, price, offer) values ('Bread - Italian Corn Meal Poly', 37.66, 19.06);
insert into items (name, price, offer) values ('Langers - Mango Nectar', 46.29, 11.22);
insert into items (name, price, offer) values ('Pasta - Fettuccine, Egg, Fresh', 28.98, 15.13);
insert into items (name, price, offer) values ('Sobe - Lizard Fuel', 17.32, 5.45);
insert into items (name, price, offer) values ('Tuna - Canned, Flaked, Light', 58.92, 16.68);
insert into items (name, price, offer) values ('Coffee Swiss Choc Almond', 61.54, 1.28);
insert into items (name, price, offer) values ('Champagne - Brights, Dry', 49.1, 15.77);
insert into items (name, price, offer) values ('Tart - Raisin And Pecan', 47.58, 15.1);
insert into items (name, price, offer) values ('Pate - Peppercorn', 29.77, 9.27);
insert into items (name, price, offer) values ('Sprite - 355 Ml', 2.72, 5.48);
insert into items (name, price, offer) values ('Venison - Liver', 86.12, 3.63);
insert into items (name, price, offer) values ('Juice - Cranberry, 341 Ml', 72.46, 6.74);
insert into items (name, price, offer) values ('Remy Red Berry Infusion', 6.52, 4.14);
insert into items (name, price, offer) values ('Chocolate - Milk', 7.25, 15.41);
insert into items (name, price, offer) values ('Flavouring Vanilla Artificial', 39.84, 5.47);
insert into items (name, price, offer) values ('Pepper - Chili Powder', 92.97, 3.9);
insert into items (name, price, offer) values ('Water - San Pellegrino', 58.03, 4.98);
insert into items (name, price, offer) values ('Cheese - Provolone', 18.62, 14.65);
insert into items (name, price, offer) values ('Cleaner - Lime Away', 50.12, 7.39);
insert into items (name, price, offer) values ('Wine - Chenin Blanc K.w.v.', 82.35, 9.68);
insert into items (name, price, offer) values ('Tarragon - Fresh', 75.94, 4.94);
insert into items (name, price, offer) values ('Onions - White', 5.46, 14.7);
insert into items (name, price, offer) values ('Compound - Orange', 64.88, 6.35);
insert into items (name, price, offer) values ('Beef - Ground Medium', 39.01, 17.79);
insert into items (name, price, offer) values ('Ham - Procutinni', 26.01, 10.29);
insert into items (name, price, offer) values ('Truffle Cups - Red', 80.79, 11.61);
insert into items (name, price, offer) values ('Cherries - Maraschino,jar', 79.07, 18.8);
insert into items (name, price, offer) values ('Urban Zen Drinks', 77.59, 1.03);
insert into items (name, price, offer) values ('Breadfruit', 44.14, 5.41);
insert into items (name, price, offer) values ('Wine - Bourgogne 2002, La', 78.26, 9.43);
insert into items (name, price, offer) values ('Coconut - Whole', 66.24, 3.71);
insert into items (name, price, offer) values ('Pepper - Green, Chili', 39.61, 3.18);
insert into items (name, price, offer) values ('Lumpfish Black', 28.39, 15.14);
insert into items (name, price, offer) values ('Zucchini - Mini, Green', 67.61, 17.64);
insert into items (name, price, offer) values ('Chicken - Thigh, Bone In', 21.01, 4.73);
insert into items (name, price, offer) values ('Soup - Clam Chowder, Dry Mix', 30.29, 9.88);
insert into items (name, price, offer) values ('Basil - Seedlings Cookstown', 70.74, 16.85);
insert into items (name, price, offer) values ('Bread - French Stick', 22.02, 2.05);
insert into items (name, price, offer) values ('Bread Base - Italian', 73.68, 10.2);
insert into items (name, price, offer) values ('Oregano - Dry, Rubbed', 52.63, 18.37);
insert into items (name, price, offer) values ('Knife Plastic - White', 35.8, 9.14);
insert into items (name, price, offer) values ('Capers - Pickled', 7.49, 15.12);
insert into items (name, price, offer) values ('Bar Special K', 96.79, 3.41);
insert into items (name, price, offer) values ('Mushroom - Chantrelle, Fresh', 3.72, 9.46);
insert into items (name, price, offer) values ('Plums - Red', 20.04, 17.03);
insert into items (name, price, offer) values ('Smoked Paprika', 72.75, 9.56);
insert into items (name, price, offer) values ('Nectarines', 77.55, 8.01);
insert into items (name, price, offer) values ('Potatoes - Yukon Gold, 80 Ct', 42.01, 19.58);
insert into items (name, price, offer) values ('Bread - Multigrain, Loaf', 12.17, 6.02);
insert into items (name, price, offer) values ('Five Alive Citrus', 45.53, 17.5);
insert into items (name, price, offer) values ('Cheese - Grie Des Champ', 5.23, 9.32);
insert into items (name, price, offer) values ('Pork - Bacon Cooked Slcd', 63.17, 12.51);
insert into items (name, price, offer) values ('Muffin Mix - Oatmeal', 94.57, 6.58);
insert into items (name, price, offer) values ('Nut - Almond, Blanched, Whole', 55.39, 10.1);
insert into items (name, price, offer) values ('Cod - Black Whole Fillet', 64.58, 19.42);
insert into items (name, price, offer) values ('Soup Campbells Turkey Veg.', 93.88, 12.17);
insert into items (name, price, offer) values ('V8 Splash Strawberry Banana', 75.26, 12.47);
insert into items (name, price, offer) values ('Lettuce - Escarole', 48.56, 12.31);
insert into items (name, price, offer) values ('Nantucket Cranberry Juice', 72.7, 18.91);
insert into items (name, price, offer) values ('Cheese - Goat', 23.7, 18.41);
insert into items (name, price, offer) values ('Teriyaki Sauce', 84.79, 11.99);
insert into items (name, price, offer) values ('Bread - Crusty Italian Poly', 91.73, 11.68);
insert into items (name, price, offer) values ('Veal Inside - Provimi', 7.3, 1.71);
insert into items (name, price, offer) values ('Ecolab - Medallion', 28.48, 15.76);
insert into items (name, price, offer) values ('Banana', 80.54, 18.85);
insert into items (name, price, offer) values ('Rabbit - Saddles', 83.93, 1.88);
insert into items (name, price, offer) values ('Chips Potato Swt Chilli Sour', 56.59, 10.72);
insert into items (name, price, offer) values ('Beef - Striploin Aa', 15.66, 17.4);
insert into items (name, price, offer) values ('Juice - V8 Splash', 46.19, 16.8);
insert into items (name, price, offer) values ('Sponge Cake Mix - Vanilla', 22.27, 17.61);
insert into items (name, price, offer) values ('Wine - Beaujolais Villages', 52.89, 14.85);
insert into items (name, price, offer) values ('Grenadine', 18.96, 16.86);
insert into items (name, price, offer) values ('Tart Shells - Savory, 2', 17.73, 3.06);
insert into items (name, price, offer) values ('Walkers Special Old Whiskey', 48.94, 17.39);
insert into items (name, price, offer) values ('Oil - Olive', 62.24, 18.04);
insert into items (name, price, offer) values ('Smoked Tongue', 28.99, 2.47);
insert into items (name, price, offer) values ('Bread - White Mini Epi', 26.29, 19.73);
insert into items (name, price, offer) values ('Peas - Frozen', 44.02, 17.55);
insert into items (name, price, offer) values ('Foam Dinner Plate', 90.07, 14.04);
insert into items (name, price, offer) values ('Chips - Potato Jalapeno', 44.25, 10.1);
insert into items (name, price, offer) values ('Goulash Seasoning', 48.73, 10.17);
insert into items (name, price, offer) values ('Raisin - Dark', 44.99, 7.36);
insert into items (name, price, offer) values ('Lychee - Canned', 64.23, 8.11);
insert into items (name, price, offer) values ('Wooden Mop Handle', 63.6, 3.57);
insert into items (name, price, offer) values ('Chicken Breast Halal', 4.45, 19.02);
insert into items (name, price, offer) values ('Soup - Canadian Pea, Dry Mix', 96.29, 14.66);
insert into items (name, price, offer) values ('Lamb - Sausage Casings', 78.16, 12.78);
insert into items (name, price, offer) values ('Bandage - Fexible 1x3', 97.84, 6.76);
insert into items (name, price, offer) values ('Lamb - Leg, Bone In', 27.94, 4.85);
insert into items (name, price, offer) values ('Veal - Inside, Choice', 12.09, 7.24);
insert into items (name, price, offer) values ('Sugar - Crumb', 80.89, 14.9);
insert into items (name, price, offer) values ('Pork - Smoked Kassler', 96.99, 7.96);
insert into items (name, price, offer) values ('Wine - Tribal Sauvignon', 68.37, 13.3);
insert into items (name, price, offer) values ('Soup - Campbells Chili Veg', 86.52, 1.19);
insert into items (name, price, offer) values ('Wine - Champagne Brut Veuve', 27.83, 18.79);
insert into items (name, price, offer) values ('Hummus - Spread', 15.44, 7.64);
insert into items (name, price, offer) values ('Appetizer - Mushroom Tart', 72.68, 8.52);
insert into items (name, price, offer) values ('Canada Dry', 5.44, 16.38);
insert into items (name, price, offer) values ('Beef - Outside, Round', 6.24, 12.58);
insert into items (name, price, offer) values ('Sausage - Meat', 45.81, 16.66);
insert into items (name, price, offer) values ('Milk - 1%', 12.88, 14.89);
insert into items (name, price, offer) values ('Chinese Foods - Cantonese', 86.96, 13.48);
insert into items (name, price, offer) values ('Oil - Olive Bertolli', 91.19, 14.34);
insert into items (name, price, offer) values ('Persimmons', 78.92, 7.38);
insert into items (name, price, offer) values ('Cabbage - Savoy', 41.96, 7.14);
insert into items (name, price, offer) values ('Cheese - Brie,danish', 21.94, 1.95);
insert into items (name, price, offer) values ('Wine - Spumante Bambino White', 56.33, 9.52);
insert into items (name, price, offer) values ('Gherkin - Sour', 86.51, 3.09);
insert into items (name, price, offer) values ('Nougat - Paste / Cream', 80.25, 17.36);
insert into items (name, price, offer) values ('Flour - All Purpose', 47.02, 3.6);
insert into items (name, price, offer) values ('Vector Energy Bar', 47.67, 16.96);
insert into items (name, price, offer) values ('Broom And Broom Rack White', 7.55, 18.21);
insert into items (name, price, offer) values ('Lamb - Ground', 61.86, 12.6);
insert into items (name, price, offer) values ('Sorrel - Fresh', 41.89, 13.68);
insert into items (name, price, offer) values ('Beef - Flank Steak', 15.55, 18.44);
insert into items (name, price, offer) values ('Syrup - Kahlua Chocolate', 82.12, 12.89);
insert into items (name, price, offer) values ('Soup - Campbells, Classic Chix', 34.83, 19.18);
insert into items (name, price, offer) values ('Island Oasis - Ice Cream Mix', 33.53, 17.88);
insert into items (name, price, offer) values ('Foil Wrap', 78.98, 17.14);
insert into items (name, price, offer) values ('Chicken Giblets', 79.47, 7.64);
insert into items (name, price, offer) values ('Bread - English Muffin', 74.22, 4.3);
insert into items (name, price, offer) values ('Isomalt', 91.13, 9.43);
insert into items (name, price, offer) values ('Towels - Paper / Kraft', 34.64, 14.3);
insert into items (name, price, offer) values ('Sachet', 11.38, 4.96);
insert into items (name, price, offer) values ('Puff Pastry - Slab', 12.33, 5.22);
insert into items (name, price, offer) values ('Cheese Cloth No 100', 54.34, 11.51);
insert into items (name, price, offer) values ('Coffee - Beans, Whole', 91.17, 3.2);
insert into items (name, price, offer) values ('Bread - Italian Sesame Poly', 51.14, 17.42);
insert into items (name, price, offer) values ('Cabbage - Red', 97.72, 7.49);
insert into items (name, price, offer) values ('Bouq All Italian - Primerba', 52.31, 6.36);
insert into items (name, price, offer) values ('Juice - Clam, 46 Oz', 86.6, 11.8);
insert into items (name, price, offer) values ('Coffee - Flavoured', 22.06, 1.26);
insert into items (name, price, offer) values ('Baking Powder', 21.23, 13.76);
insert into items (name, price, offer) values ('Cheese - Taleggio D.o.p.', 5.75, 6.86);
insert into items (name, price, offer) values ('Nut - Peanut, Roasted', 31.06, 17.43);
insert into items (name, price, offer) values ('Soup - Beef, Base Mix', 5.03, 9.89);
insert into items (name, price, offer) values ('Extract - Rum', 31.55, 14.89);
insert into items (name, price, offer) values ('Ham - Proscuitto', 19.18, 9.28);
insert into items (name, price, offer) values ('Soap - Hand Soap', 4.0, 7.86);
insert into items (name, price, offer) values ('Potatoes - Instant, Mashed', 36.77, 9.78);
insert into items (name, price, offer) values ('Sauce - Bernaise, Mix', 12.59, 4.39);
insert into items (name, price, offer) values ('Beans - Fava, Canned', 69.63, 17.99);
insert into items (name, price, offer) values ('Potatoes - Purple, Organic', 10.04, 17.44);
insert into items (name, price, offer) values ('Cheese - Feta', 35.94, 12.77);
insert into items (name, price, offer) values ('Mushroom - King Eryingii', 83.95, 7.02);
insert into items (name, price, offer) values ('Energy Drink - Franks Original', 55.56, 7.59);
insert into items (name, price, offer) values ('Apple - Fuji', 78.98, 18.61);
insert into items (name, price, offer) values ('Lamb Rack Frenched Australian', 95.65, 8.89);
insert into items (name, price, offer) values ('Wine - Vovray Sec Domaine Huet', 84.71, 17.69);
insert into items (name, price, offer) values ('Carrots - Mini Red Organic', 65.49, 7.54);
insert into items (name, price, offer) values ('Wine - Red, Gallo, Merlot', 83.43, 15.92);
insert into items (name, price, offer) values ('Milk - Skim', 21.25, 8.0);
insert into items (name, price, offer) values ('Fork - Plastic', 24.25, 19.49);
insert into items (name, price, offer) values ('Carbonated Water - Wildberry', 96.8, 15.73);
insert into items (name, price, offer) values ('Salt And Pepper Mix - Black', 85.32, 1.8);
insert into items (name, price, offer) values ('Wine - Spumante Bambino White', 65.18, 9.75);
insert into items (name, price, offer) values ('Puree - Passion Fruit', 31.44, 2.31);
insert into items (name, price, offer) values ('Otomegusa Dashi Konbu', 77.28, 9.34);
insert into items (name, price, offer) values ('Coffee - French Vanilla Frothy', 12.32, 3.97);
insert into items (name, price, offer) values ('Muffin Orange Individual', 62.28, 9.21);
insert into items (name, price, offer) values ('Pastry - French Mini Assorted', 37.31, 10.4);
insert into items (name, price, offer) values ('Okra', 21.51, 4.98);
insert into items (name, price, offer) values ('Snapple Raspberry Tea', 20.53, 2.63);
insert into items (name, price, offer) values ('Wine - Sawmill Creek Autumn', 57.15, 8.87);
insert into items (name, price, offer) values ('Mousse - Mango', 54.33, 6.62);
insert into items (name, price, offer) values ('Beans - Navy, Dry', 28.93, 3.68);
insert into items (name, price, offer) values ('Butter Ripple - Phillips', 18.49, 10.44);
insert into items (name, price, offer) values ('Apples - Sliced / Wedge', 75.36, 5.05);
insert into items (name, price, offer) values ('Tomatoes - Roma', 45.37, 1.75);
insert into items (name, price, offer) values ('Flavouring - Raspberry', 19.31, 7.7);
insert into items (name, price, offer) values ('Tea - Lemon Scented', 76.64, 19.56);
insert into items (name, price, offer) values ('Sauce - Sesame Thai Dressing', 24.32, 2.75);
insert into items (name, price, offer) values ('Flower - Carnations', 10.75, 18.29);
insert into items (name, price, offer) values ('Pork - Butt, Boneless', 36.46, 14.3);
insert into items (name, price, offer) values ('Cup - 6oz, Foam', 21.72, 13.59);
insert into items (name, price, offer) values ('Truffle Shells - Semi - Sweet', 11.13, 17.68);
insert into items (name, price, offer) values ('Aspic - Clear', 59.35, 6.25);
insert into items (name, price, offer) values ('Crackers Cheez It', 91.51, 11.78);
insert into items (name, price, offer) values ('Pernod', 68.49, 1.32);
insert into items (name, price, offer) values ('Turnip - White, Organic', 57.04, 19.69);
insert into items (name, price, offer) values ('Scallops 60/80 Iqf', 32.35, 4.88);
insert into items (name, price, offer) values ('Tia Maria', 51.92, 18.81);
insert into items (name, price, offer) values ('Creme De Banane - Marie', 70.49, 13.7);
insert into items (name, price, offer) values ('Chilli Paste, Ginger Garlic', 76.6, 8.7);
insert into items (name, price, offer) values ('Onions - Dried, Chopped', 70.28, 13.38);
insert into items (name, price, offer) values ('Cardamon Seed / Pod', 12.32, 1.39);
insert into items (name, price, offer) values ('Soup - Base Broth Beef', 41.66, 4.95);
insert into items (name, price, offer) values ('Wine - Port Late Bottled Vintage', 72.86, 5.72);
insert into items (name, price, offer) values ('Veal - Kidney', 23.82, 17.26);
insert into items (name, price, offer) values ('Cheese Cloth', 27.82, 12.92);
insert into items (name, price, offer) values ('Tofu - Soft', 33.44, 9.74);
insert into items (name, price, offer) values ('Juice - V8 Splash', 51.11, 3.15);
insert into items (name, price, offer) values ('Syrup - Kahlua Chocolate', 88.76, 7.02);
insert into items (name, price, offer) values ('Doilies - 8, Paper', 28.77, 9.66);
insert into items (name, price, offer) values ('Maintenance Removal Charge', 83.14, 14.2);
insert into items (name, price, offer) values ('Pail - 4l White, With Handle', 31.75, 14.61);
insert into items (name, price, offer) values ('Soup - Campbells, Lentil', 93.06, 8.91);
insert into items (name, price, offer) values ('Thermometer Digital', 42.8, 7.19);
insert into items (name, price, offer) values ('Rabbit - Saddles', 7.52, 18.94);
insert into items (name, price, offer) values ('Broom And Broom Rack White', 85.63, 4.59);
insert into items (name, price, offer) values ('Puree - Pear', 95.59, 7.05);
insert into items (name, price, offer) values ('Egg - Salad Premix', 59.73, 5.83);
insert into items (name, price, offer) values ('Wine - Masi Valpolocell', 88.44, 17.39);
insert into items (name, price, offer) values ('Squid U5 - Thailand', 40.78, 14.85);
insert into items (name, price, offer) values ('Nantucket Pine Orangebanana', 76.04, 14.02);
insert into items (name, price, offer) values ('Shrimp - Black Tiger 13/15', 35.82, 6.84);
insert into items (name, price, offer) values ('Calypso - Lemonade', 25.27, 18.58);
insert into items (name, price, offer) values ('Cheese - St. Andre', 34.29, 8.94);
insert into items (name, price, offer) values ('Muffin Mix - Morning Glory', 18.9, 2.83);
insert into items (name, price, offer) values ('Pineapple - Golden', 31.84, 8.36);
insert into items (name, price, offer) values ('Veal - Insides Provini', 4.14, 17.82);
insert into items (name, price, offer) values ('Stock - Chicken, White', 88.81, 4.05);
insert into items (name, price, offer) values ('Bread - Hamburger Buns', 59.36, 5.63);
insert into items (name, price, offer) values ('Crackers - Soda / Saltins', 38.29, 19.14);
insert into items (name, price, offer) values ('Plate Pie Foil', 2.68, 2.16);
insert into items (name, price, offer) values ('Melon - Cantaloupe', 86.09, 6.77);
insert into items (name, price, offer) values ('Island Oasis - Mango Daiquiri', 47.41, 1.84);
insert into items (name, price, offer) values ('Shrimp - 150 - 250', 13.39, 5.93);
insert into items (name, price, offer) values ('Bread - Sticks, Thin, Plain', 69.76, 12.21);
insert into items (name, price, offer) values ('Onions - Pearl', 16.97, 6.96);
insert into items (name, price, offer) values ('Beef Wellington', 12.77, 11.42);
insert into items (name, price, offer) values ('Onions - Green', 90.05, 16.18);
insert into items (name, price, offer) values ('Slt - Individual Portions', 64.63, 8.93);
insert into items (name, price, offer) values ('Icecream Bar - Del Monte', 88.61, 15.22);
insert into items (name, price, offer) values ('Napkin - Cocktail,beige 2 - Ply', 85.37, 16.91);
insert into items (name, price, offer) values ('Extract - Rum', 78.7, 7.75);
insert into items (name, price, offer) values ('Pumpkin - Seed', 42.57, 15.04);
insert into items (name, price, offer) values ('Sugar - Sweet N Low, Individual', 62.02, 1.85);
insert into items (name, price, offer) values ('Apple - Macintosh', 54.57, 4.73);
insert into items (name, price, offer) values ('Bread Base - Goodhearth', 47.85, 5.96);
insert into items (name, price, offer) values ('Beer - Heinekin', 85.22, 4.89);
insert into items (name, price, offer) values ('Soupfoamcont12oz 112con', 16.37, 6.45);
insert into items (name, price, offer) values ('Taro Root', 34.3, 12.86);
insert into items (name, price, offer) values ('Muffin - Mix - Creme Brule 15l', 39.77, 16.8);
insert into items (name, price, offer) values ('Cookies - Englishbay Oatmeal', 74.78, 14.72);
insert into items (name, price, offer) values ('Zucchini - Green', 41.67, 8.47);
insert into items (name, price, offer) values ('Pear - Packum', 17.44, 19.45);
insert into items (name, price, offer) values ('Stock - Beef, Brown', 47.13, 1.1);
insert into items (name, price, offer) values ('Chicken - Leg / Back Attach', 12.63, 15.36);
insert into items (name, price, offer) values ('Wine - Prem Select Charddonany', 55.95, 12.19);
insert into items (name, price, offer) values ('Wine - Conde De Valdemar', 6.17, 6.85);
insert into items (name, price, offer) values ('Pear - Prickly', 49.7, 9.79);
insert into items (name, price, offer) values ('Sausage - Chorizo', 25.46, 19.74);
insert into items (name, price, offer) values ('Wine - Red Oakridge Merlot', 43.4, 8.99);
insert into items (name, price, offer) values ('Danishes - Mini Cheese', 49.4, 10.73);
insert into items (name, price, offer) values ('Cassis', 51.57, 19.94);
insert into items (name, price, offer) values ('Bagel - Everything', 57.56, 14.96);
insert into items (name, price, offer) values ('Lettuce - Romaine', 67.67, 15.43);
insert into items (name, price, offer) values ('Dish Towel', 70.13, 14.15);
insert into items (name, price, offer) values ('Crush - Cream Soda', 67.54, 2.21);
insert into items (name, price, offer) values ('Shrimp - Black Tiger 16/20', 11.21, 10.85);
insert into items (name, price, offer) values ('Wine - Two Oceans Sauvignon', 77.39, 6.94);
insert into items (name, price, offer) values ('Lighter - Bbq', 30.04, 9.82);
insert into items (name, price, offer) values ('Sage Ground Wiberg', 29.04, 2.1);
insert into items (name, price, offer) values ('Mushroom - King Eryingii', 48.4, 19.32);
insert into items (name, price, offer) values ('Goat - Leg', 71.72, 14.23);
insert into items (name, price, offer) values ('Sauce - White, Mix', 12.94, 16.11);
insert into items (name, price, offer) values ('Lamb - Shoulder', 78.71, 11.82);
insert into items (name, price, offer) values ('Chicken - Base, Ultimate', 40.01, 15.05);
insert into items (name, price, offer) values ('Juice - Ocean Spray Cranberry', 20.19, 1.42);
insert into items (name, price, offer) values ('Watercress', 69.81, 12.37);
insert into items (name, price, offer) values ('Olives - Black, Pitted', 73.6, 19.54);
insert into items (name, price, offer) values ('Wine - Cousino Macul Antiguas', 62.94, 5.37);
insert into items (name, price, offer) values ('Longos - Cheese Tortellini', 22.28, 4.32);
insert into items (name, price, offer) values ('Durian Fruit', 97.26, 17.96);
insert into items (name, price, offer) values ('Gherkin', 96.0, 9.44);
insert into items (name, price, offer) values ('Nut - Pumpkin Seeds', 42.66, 9.18);
insert into items (name, price, offer) values ('Curry Paste - Green Masala', 93.24, 4.9);
insert into items (name, price, offer) values ('Squash - Acorn', 9.99, 17.91);
insert into items (name, price, offer) values ('Wine - Ice Wine', 87.53, 13.58);
insert into items (name, price, offer) values ('Oats Large Flake', 14.87, 9.17);
insert into items (name, price, offer) values ('Oats Large Flake', 92.24, 14.79);
insert into items (name, price, offer) values ('Table Cloth 53x53 White', 28.85, 13.31);
insert into items (name, price, offer) values ('Truffle Shells - Semi - Sweet', 85.34, 9.28);
insert into items (name, price, offer) values ('Jameson - Irish Whiskey', 2.7, 4.65);
insert into items (name, price, offer) values ('Sauce - Hollandaise', 22.66, 5.81);
insert into items (name, price, offer) values ('Crackers - Melba Toast', 25.07, 7.23);
insert into items (name, price, offer) values ('Bar Mix - Pina Colada, 355 Ml', 6.1, 14.83);
insert into items (name, price, offer) values ('Butter - Salted', 4.5, 13.76);
insert into items (name, price, offer) values ('Cake - Bande Of Fruit', 61.26, 19.1);
insert into items (name, price, offer) values ('Aspic - Clear', 26.39, 19.04);
insert into items (name, price, offer) values ('Venison - Ground', 60.96, 2.77);
insert into items (name, price, offer) values ('Artichokes - Knobless, White', 37.48, 6.7);
insert into items (name, price, offer) values ('Bread - Raisin Walnut Oval', 26.3, 12.22);
insert into items (name, price, offer) values ('Venison - Denver Leg Boneless', 7.9, 19.47);
insert into items (name, price, offer) values ('Beans - Kidney White', 56.15, 8.51);
insert into items (name, price, offer) values ('Tea - Camomele', 17.77, 18.17);
insert into items (name, price, offer) values ('Bread - Bagels, Plain', 59.28, 3.5);
insert into items (name, price, offer) values ('Chicken - Base', 61.29, 4.31);
insert into items (name, price, offer) values ('Oil - Macadamia', 1.98, 4.26);
insert into items (name, price, offer) values ('Coffee Decaf Colombian', 73.95, 8.29);
insert into items (name, price, offer) values ('Apricots - Halves', 12.26, 11.94);
insert into items (name, price, offer) values ('Oil - Coconut', 51.47, 16.45);
insert into items (name, price, offer) values ('Tomatoes - Heirloom', 21.83, 17.15);
insert into items (name, price, offer) values ('Apples - Sliced / Wedge', 56.56, 15.51);
insert into items (name, price, offer) values ('Ham - Cooked Bayonne Tinned', 94.01, 2.02);
insert into items (name, price, offer) values ('Turkey - Whole, Fresh', 83.28, 3.58);
insert into items (name, price, offer) values ('Chip - Potato Dill Pickle', 59.11, 2.85);
insert into items (name, price, offer) values ('Bacon Strip Precooked', 19.79, 12.52);
insert into items (name, price, offer) values ('Ham - Virginia', 31.39, 10.15);
insert into items (name, price, offer) values ('Sauce - Caesar Dressing', 37.04, 5.19);
insert into items (name, price, offer) values ('Apple - Macintosh', 33.25, 2.23);
insert into items (name, price, offer) values ('Filter - Coffee', 39.86, 13.3);
insert into items (name, price, offer) values ('Lid - 10,12,16 Oz', 93.81, 18.53);
insert into items (name, price, offer) values ('Coriander - Seed', 48.39, 10.71);
insert into items (name, price, offer) values ('Juice - Tomato, 10 Oz', 39.34, 16.17);
insert into items (name, price, offer) values ('Bread Roll Foccacia', 22.1, 9.13);
insert into items (name, price, offer) values ('Calypso - Black Cherry Lemonade', 78.58, 1.92);
insert into items (name, price, offer) values ('Trout - Smoked', 37.91, 4.33);
insert into items (name, price, offer) values ('Tuna - Yellowfin', 9.95, 8.2);
insert into items (name, price, offer) values ('Fib N9 - Prague Powder', 96.53, 10.5);
insert into items (name, price, offer) values ('Vodka - Smirnoff', 77.96, 11.06);
insert into items (name, price, offer) values ('Mangoes', 72.02, 18.05);
insert into items (name, price, offer) values ('Wine - Magnotta - Red, Baco', 57.08, 11.4);
insert into items (name, price, offer) values ('Chocolate - Dark', 86.47, 10.94);
insert into items (name, price, offer) values ('Cucumber - English', 2.78, 18.34);
insert into items (name, price, offer) values ('Bagelers', 69.43, 8.14);
insert into items (name, price, offer) values ('Spring Roll Veg Mini', 64.16, 16.97);
insert into items (name, price, offer) values ('Wine - Ruffino Chianti', 98.5, 8.55);
insert into items (name, price, offer) values ('Wine - Red, Pelee Island Merlot', 94.29, 9.77);
insert into items (name, price, offer) values ('Truffle Shells - Semi - Sweet', 53.1, 8.97);
insert into items (name, price, offer) values ('Beef - Kobe Striploin', 73.7, 9.88);
insert into items (name, price, offer) values ('Gatorade - Cool Blue Raspberry', 40.32, 7.84);
insert into items (name, price, offer) values ('Beer - Sleemans Honey Brown', 59.83, 13.07);
insert into items (name, price, offer) values ('Grapes - Green', 13.97, 17.23);
insert into items (name, price, offer) values ('Puree - Pear', 3.06, 10.57);
insert into items (name, price, offer) values ('Versatainer Nc - 8288', 41.24, 9.07);
insert into items (name, price, offer) values ('Vermouth - White, Cinzano', 82.9, 13.24);
insert into items (name, price, offer) values ('Soup - Campbells Chili', 30.4, 2.67);
insert into items (name, price, offer) values ('English Muffin', 6.17, 8.87);
insert into items (name, price, offer) values ('Cilantro / Coriander - Fresh', 83.46, 6.97);
insert into items (name, price, offer) values ('Blouse / Shirt / Sweater', 63.6, 17.29);
insert into items (name, price, offer) values ('Vodka - Smirnoff', 10.83, 11.03);
insert into items (name, price, offer) values ('Cucumber - English', 2.65, 5.07);
insert into items (name, price, offer) values ('Breakfast Quesadillas', 70.85, 18.79);
insert into items (name, price, offer) values ('Tomatoes - Cherry, Yellow', 41.23, 2.98);
insert into items (name, price, offer) values ('Couscous', 91.53, 2.27);
insert into items (name, price, offer) values ('Oil - Canola', 32.46, 18.85);
insert into items (name, price, offer) values ('Pastry - Butterscotch Baked', 4.41, 16.83);
insert into items (name, price, offer) values ('Beets - Candy Cane, Organic', 75.01, 3.43);
insert into items (name, price, offer) values ('Soup - Campbells Mac N Cheese', 78.38, 1.73);
insert into items (name, price, offer) values ('Broom Handle', 44.14, 17.18);
insert into items (name, price, offer) values ('Pasta - Rotini, Colour, Dry', 50.62, 15.02);
insert into items (name, price, offer) values ('Bread - Roll, Whole Wheat', 51.4, 11.87);
insert into items (name, price, offer) values ('Soup - Campbells Bean Medley', 90.69, 17.93);
insert into items (name, price, offer) values ('Chicken Giblets', 95.21, 6.5);
insert into items (name, price, offer) values ('Wine - White, Pelee Island', 5.76, 14.85);
insert into items (name, price, offer) values ('Flour Pastry Super Fine', 10.12, 8.64);
insert into items (name, price, offer) values ('Veal Inside - Provimi', 69.98, 7.88);
insert into items (name, price, offer) values ('Tray - 12in Rnd Blk', 53.31, 8.21);
insert into items (name, price, offer) values ('Flour - Fast / Rapid', 8.49, 3.91);
insert into items (name, price, offer) values ('Hersey Shakes', 91.27, 1.81);
insert into items (name, price, offer) values ('Wine - Jafflin Bourgongone', 72.0, 7.12);
insert into items (name, price, offer) values ('Venison - Ground', 68.71, 18.69);
insert into items (name, price, offer) values ('Wiberg Cure', 10.0, 3.99);
insert into items (name, price, offer) values ('Pastry - Key Limepoppy Seed Tea', 67.97, 14.92);
insert into items (name, price, offer) values ('Wine - Two Oceans Sauvignon', 63.22, 9.22);
insert into items (name, price, offer) values ('Barley - Pearl', 41.41, 1.21);
insert into items (name, price, offer) values ('Mushroom - Lg - Cello', 14.75, 7.91);
insert into items (name, price, offer) values ('Mcguinness - Blue Curacao', 85.91, 2.51);
insert into items (name, price, offer) values ('Onion - Dried', 46.4, 1.42);
insert into items (name, price, offer) values ('Table Cloth 62x114 Colour', 44.29, 5.8);
insert into items (name, price, offer) values ('Nut - Chestnuts, Whole', 82.77, 1.31);
insert into items (name, price, offer) values ('Garlic Powder', 62.04, 11.01);
insert into items (name, price, offer) values ('Coffee Swiss Choc Almond', 51.44, 3.15);
insert into items (name, price, offer) values ('Mudslide', 37.88, 6.58);
insert into items (name, price, offer) values ('Pork - Caul Fat', 23.18, 8.45);
insert into items (name, price, offer) values ('Sauce - Fish 25 Ozf Bottle', 53.34, 10.52);
insert into items (name, price, offer) values ('Cookie Dough - Chocolate Chip', 88.44, 6.01);
insert into items (name, price, offer) values ('Soupfoamcont12oz 112con', 13.49, 18.66);
insert into items (name, price, offer) values ('Sorrel - Fresh', 67.04, 19.23);
insert into items (name, price, offer) values ('Pastry - Cheese Baked Scones', 46.25, 7.64);
insert into items (name, price, offer) values ('Sproutsmustard Cress', 39.25, 16.48);
insert into items (name, price, offer) values ('Energy Drink Red Bull', 9.59, 15.14);
insert into items (name, price, offer) values ('Soup - Knorr, Country Bean', 22.62, 12.93);
insert into items (name, price, offer) values ('Mayonnaise', 57.98, 4.42);
insert into items (name, price, offer) values ('Sugar - Invert', 63.65, 19.49);
insert into items (name, price, offer) values ('Arizona - Green Tea', 77.74, 12.66);
insert into items (name, price, offer) values ('Tomatoes Tear Drop', 7.24, 4.93);
insert into items (name, price, offer) values ('Artichoke - Fresh', 93.17, 18.96);
insert into items (name, price, offer) values ('Ocean Spray - Kiwi Strawberry', 69.52, 13.68);
insert into items (name, price, offer) values ('Sorrel - Fresh', 84.74, 7.17);
insert into items (name, price, offer) values ('Wine - Chablis J Moreau Et Fils', 78.69, 18.83);
insert into items (name, price, offer) values ('Rice Pilaf, Dry,package', 24.43, 9.96);
insert into items (name, price, offer) values ('Muffin - Bran Ind Wrpd', 53.91, 2.33);
insert into items (name, price, offer) values ('Wine - Sauvignon Blanc Oyster', 41.4, 7.93);
insert into items (name, price, offer) values ('Wine - Ruffino Chianti', 49.69, 13.77);
insert into items (name, price, offer) values ('Mayonnaise', 99.25, 8.05);
insert into items (name, price, offer) values ('Foam Tray S2', 22.28, 17.82);
insert into items (name, price, offer) values ('Coffee - Almond Amaretto', 64.36, 9.4);
insert into items (name, price, offer) values ('Yogurt - Peach, 175 Gr', 78.2, 18.47);
insert into items (name, price, offer) values ('Spring Roll Wrappers', 84.69, 6.64);
insert into items (name, price, offer) values ('Molasses - Fancy', 3.98, 1.04);
insert into items (name, price, offer) values ('Wine - Guy Sage Touraine', 96.57, 10.1);
insert into items (name, price, offer) values ('Spinach - Packaged', 76.24, 9.56);
insert into items (name, price, offer) values ('Bar - Sweet And Salty Chocolate', 74.09, 10.51);
insert into items (name, price, offer) values ('Monkfish - Fresh', 66.05, 3.85);
insert into items (name, price, offer) values ('Lamb - Ground', 92.21, 8.65);
insert into items (name, price, offer) values ('Apricots Fresh', 26.9, 16.31);
insert into items (name, price, offer) values ('Chicken - White Meat With Tender', 2.01, 2.86);
insert into items (name, price, offer) values ('Crab - Claws, Snow 16 - 24', 32.73, 2.8);
insert into items (name, price, offer) values ('Danishes - Mini Cheese', 84.12, 19.14);
insert into items (name, price, offer) values ('Island Oasis - Sweet And Sour Mix', 96.18, 6.43);
insert into items (name, price, offer) values ('Jerusalem Artichoke', 94.92, 11.47);
insert into items (name, price, offer) values ('Dried Cranberries', 16.82, 15.33);
insert into items (name, price, offer) values ('Wine - Acient Coast Caberne', 85.41, 2.97);
insert into items (name, price, offer) values ('Bread - Bistro Sour', 19.18, 10.0);
insert into items (name, price, offer) values ('Napkin White', 77.29, 10.44);
insert into items (name, price, offer) values ('Rum - Coconut, Malibu', 69.93, 6.42);
insert into items (name, price, offer) values ('Croissants Thaw And Serve', 59.39, 17.46);
insert into items (name, price, offer) values ('Capon - Whole', 16.84, 17.0);
insert into items (name, price, offer) values ('Squash - Pattypan, Yellow', 79.72, 7.66);
insert into items (name, price, offer) values ('Beef - Ground Medium', 22.88, 5.31);
insert into items (name, price, offer) values ('Grapes - Green', 1.35, 17.93);
insert into items (name, price, offer) values ('Scampi Tail', 58.17, 18.7);
insert into items (name, price, offer) values ('Cheese - Montery Jack', 4.61, 13.3);
insert into items (name, price, offer) values ('Ecolab - Lime - A - Way 4/4 L', 26.35, 7.1);
insert into items (name, price, offer) values ('Pie Shell - 9', 88.69, 7.11);
insert into items (name, price, offer) values ('Bread Base - Toscano', 38.13, 18.99);
insert into items (name, price, offer) values ('Pickerel - Fillets', 91.72, 19.82);
insert into items (name, price, offer) values ('Nut - Pistachio, Shelled', 12.86, 6.74);
insert into items (name, price, offer) values ('Pancetta', 16.25, 13.2);
insert into items (name, price, offer) values ('Flower - Potmums', 88.44, 13.29);
insert into items (name, price, offer) values ('Pasta - Bauletti, Chicken White', 67.36, 2.48);
insert into items (name, price, offer) values ('Brownies - Two Bite, Chocolate', 70.54, 15.0);
insert into items (name, price, offer) values ('Trout - Smoked', 92.81, 10.35);
insert into items (name, price, offer) values ('Pork - Backs - Boneless', 61.24, 7.99);
insert into items (name, price, offer) values ('Kaffir Lime Leaves', 22.25, 3.44);
insert into items (name, price, offer) values ('Pepper - Chillies, Crushed', 54.94, 11.79);
insert into items (name, price, offer) values ('Beer - Blue Light', 60.21, 17.18);
insert into items (name, price, offer) values ('Juice - V8 Splash', 26.27, 11.1);
insert into items (name, price, offer) values ('Quail - Jumbo Boneless', 46.26, 13.27);
insert into items (name, price, offer) values ('Island Oasis - Raspberry', 13.4, 12.51);
insert into items (name, price, offer) values ('True - Vue Containers', 72.97, 18.46);
insert into items (name, price, offer) values ('Butter Balls Salted', 91.97, 12.48);
insert into items (name, price, offer) values ('Beans - Kidney, Red Dry', 7.99, 11.57);
insert into items (name, price, offer) values ('Skewers - Bamboo', 5.26, 2.87);
insert into items (name, price, offer) values ('Wine - Coteaux Du Tricastin Ac', 77.59, 7.46);
insert into items (name, price, offer) values ('Crackers Cheez It', 55.33, 16.15);
insert into items (name, price, offer) values ('Anchovy In Oil', 84.29, 19.68);
insert into items (name, price, offer) values ('Sping Loaded Cup Dispenser', 58.35, 8.89);
insert into items (name, price, offer) values ('Beer - Original Organic Lager', 60.38, 12.1);
insert into items (name, price, offer) values ('Pomegranates', 24.6, 19.91);
insert into items (name, price, offer) values ('Pastry - Apple Muffins - Mini', 34.07, 8.24);
insert into items (name, price, offer) values ('Beans - Navy, Dry', 18.93, 10.06);
insert into items (name, price, offer) values ('Bread Crumbs - Japanese Style', 77.54, 2.47);
insert into items (name, price, offer) values ('Fennel - Seeds', 21.92, 16.61);
insert into items (name, price, offer) values ('Whmis Spray Bottle Graduated', 31.38, 6.64);
insert into items (name, price, offer) values ('Pepper - Paprika, Spanish', 72.97, 14.59);
insert into items (name, price, offer) values ('Puree - Mango', 63.7, 3.09);
insert into items (name, price, offer) values ('Allspice - Jamaican', 7.28, 18.84);
insert into items (name, price, offer) values ('Mop Head - Cotton, 24 Oz', 78.69, 12.38);
insert into items (name, price, offer) values ('Syrup - Monin - Granny Smith', 85.8, 3.43);
insert into items (name, price, offer) values ('Cheese - Camembert', 60.69, 8.0);
insert into items (name, price, offer) values ('Schnappes - Peach, Walkers', 70.54, 17.39);
insert into items (name, price, offer) values ('Ginger - Ground', 58.23, 7.83);
insert into items (name, price, offer) values ('Mix - Cocktail Ice Cream', 8.52, 12.49);
insert into items (name, price, offer) values ('Hold Up Tool Storage Rack', 26.35, 16.75);
insert into items (name, price, offer) values ('Watercress', 3.86, 5.63);
insert into items (name, price, offer) values ('Syrup - Monin - Granny Smith', 36.59, 11.55);
insert into items (name, price, offer) values ('Carrots - Mini, Stem On', 11.55, 17.97);
insert into items (name, price, offer) values ('Shallots', 31.38, 13.43);
insert into items (name, price, offer) values ('Milk - Homo', 92.44, 13.12);
insert into items (name, price, offer) values ('Truffle Paste', 55.36, 10.54);
insert into items (name, price, offer) values ('Parsley Italian - Fresh', 41.62, 18.3);
insert into items (name, price, offer) values ('Mushroom - Enoki, Dry', 70.77, 19.72);
insert into items (name, price, offer) values ('Doilies - 8, Paper', 47.35, 3.75);
insert into items (name, price, offer) values ('Wine - Jafflin Bourgongone', 92.8, 16.6);
insert into items (name, price, offer) values ('Mushroom - Enoki, Dry', 65.28, 13.56);
insert into items (name, price, offer) values ('Lid - Translucent, 3.5 And 6 Oz', 2.93, 3.07);
insert into items (name, price, offer) values ('Flour Dark Rye', 13.74, 17.44);
insert into items (name, price, offer) values ('Sauce - Apple, Unsweetened', 23.78, 13.24);
insert into items (name, price, offer) values ('Bread - Sticks, Thin, Plain', 60.51, 11.07);
insert into items (name, price, offer) values ('Godiva White Chocolate', 51.42, 18.2);
insert into items (name, price, offer) values ('Pastry - Trippleberry Muffin - Mini', 81.29, 7.56);
insert into items (name, price, offer) values ('Bread Crumbs - Japanese Style', 25.6, 9.9);
insert into items (name, price, offer) values ('Chocolate - Feathers', 38.54, 5.86);
insert into items (name, price, offer) values ('Appetiser - Bought', 89.76, 7.51);
insert into items (name, price, offer) values ('Chip - Potato Dill Pickle', 63.73, 1.1);
insert into items (name, price, offer) values ('Milk - Chocolate 500ml', 18.65, 11.5);
insert into items (name, price, offer) values ('Lettuce - Treviso', 4.8, 15.97);
insert into items (name, price, offer) values ('Coffee Decaf Colombian', 3.79, 7.78);
insert into items (name, price, offer) values ('Wine - Pinot Noir Latour', 22.24, 5.79);
insert into items (name, price, offer) values ('Foam Tray S2', 37.55, 3.84);
insert into items (name, price, offer) values ('Scotch - Queen Anne', 35.38, 1.25);
insert into items (name, price, offer) values ('Broom And Broom Rack White', 44.74, 7.42);
insert into items (name, price, offer) values ('Tart - Raisin And Pecan', 64.42, 10.77);
insert into items (name, price, offer) values ('Magnotta Bel Paese Red', 25.06, 7.75);
insert into items (name, price, offer) values ('Amaretto', 18.17, 11.36);
insert into items (name, price, offer) values ('Venison - Denver Leg Boneless', 77.52, 5.77);
insert into items (name, price, offer) values ('Table Cloth 144x90 White', 6.12, 19.47);
insert into items (name, price, offer) values ('Ecolab Digiclean Mild Fm', 75.02, 18.24);
insert into items (name, price, offer) values ('Onion - Dried', 76.54, 12.27);
insert into items (name, price, offer) values ('Glaze - Apricot', 13.09, 6.69);
insert into items (name, price, offer) values ('Beans - Fava Fresh', 88.6, 16.01);
insert into items (name, price, offer) values ('Tart Shells - Barquettes, Savory', 17.7, 8.94);
insert into items (name, price, offer) values ('Yogurt - Raspberry, 175 Gr', 16.18, 10.25);
insert into items (name, price, offer) values ('Wine - Red, Concha Y Toro', 96.64, 16.12);
insert into items (name, price, offer) values ('Maple Syrup', 57.7, 14.97);
insert into items (name, price, offer) values ('Saskatoon Berries - Frozen', 41.76, 15.51);
insert into items (name, price, offer) values ('Tea Leaves - Oolong', 77.05, 19.25);
insert into items (name, price, offer) values ('Scotch - Queen Anne', 2.76, 14.55);
insert into items (name, price, offer) values ('Basil - Seedlings Cookstown', 16.47, 10.82);
insert into items (name, price, offer) values ('Cinnamon Buns Sticky', 2.23, 9.99);
insert into items (name, price, offer) values ('Bread Roll Foccacia', 39.71, 18.84);
insert into items (name, price, offer) values ('Napkin - Beverage 1 Ply', 69.63, 8.63);
insert into items (name, price, offer) values ('Soup - Campbells, Cream Of', 52.91, 2.39);
insert into items (name, price, offer) values ('Appetizer - Chicken Satay', 8.52, 9.51);
insert into items (name, price, offer) values ('Ham Black Forest', 34.84, 4.23);
insert into items (name, price, offer) values ('Lobster - Live', 10.63, 13.0);
insert into items (name, price, offer) values ('Cheese - Cheddar, Old White', 6.36, 14.13);
insert into items (name, price, offer) values ('Scallops 60/80 Iqf', 89.22, 12.9);
insert into items (name, price, offer) values ('Tomato Puree', 61.96, 7.42);
insert into items (name, price, offer) values ('Mortadella', 68.62, 5.98);
insert into items (name, price, offer) values ('Lamb - Whole Head Off', 50.9, 16.37);
insert into items (name, price, offer) values ('Carbonated Water - Orange', 84.83, 11.2);
insert into items (name, price, offer) values ('Appetizer - Chicken Satay', 16.88, 3.22);
insert into items (name, price, offer) values ('Soup Bowl Clear 8oz92008', 91.49, 14.07);
insert into items (name, price, offer) values ('Beer - Upper Canada Lager', 93.51, 16.79);
insert into items (name, price, offer) values ('Beans - Long, Chinese', 19.3, 6.02);
insert into items (name, price, offer) values ('Oil - Olive, Extra Virgin', 55.56, 3.22);
insert into items (name, price, offer) values ('The Pop Shoppe - Cream Soda', 19.74, 16.46);
insert into items (name, price, offer) values ('Gelatine Leaves - Envelopes', 73.37, 13.76);
insert into items (name, price, offer) values ('Chocolate - Milk', 66.71, 13.59);
insert into items (name, price, offer) values ('Pasta - Cheese / Spinach Bauletti', 54.33, 13.43);
insert into items (name, price, offer) values ('Beef - Rib Roast, Capless', 95.81, 9.66);
insert into items (name, price, offer) values ('Tortillas - Flour, 12', 32.2, 17.08);
insert into items (name, price, offer) values ('Container - Clear 32 Oz', 19.13, 2.83);
insert into items (name, price, offer) values ('Sage Ground Wiberg', 38.24, 12.84);
insert into items (name, price, offer) values ('Cactus Pads', 15.93, 16.66);
insert into items (name, price, offer) values ('Fireball Whisky', 9.82, 7.87);
insert into items (name, price, offer) values ('Juice - Pineapple, 341 Ml', 26.48, 19.25);
insert into items (name, price, offer) values ('Table Cloth 54x72 White', 11.07, 15.57);
insert into items (name, price, offer) values ('Nut - Almond, Blanched, Sliced', 77.17, 11.33);
insert into items (name, price, offer) values ('Carbonated Water - Lemon Lime', 61.44, 12.32);
insert into items (name, price, offer) values ('Clams - Littleneck, Whole', 73.3, 12.33);
insert into items (name, price, offer) values ('Sauce - Alfredo', 53.69, 4.69);
insert into items (name, price, offer) values ('Eggplant - Baby', 15.25, 12.5);
insert into items (name, price, offer) values ('Cloves - Ground', 70.26, 16.58);
insert into items (name, price, offer) values ('Cheese - Colby', 89.25, 14.45);
insert into items (name, price, offer) values ('Bacardi Breezer - Tropical', 14.66, 15.56);
insert into items (name, price, offer) values ('Steampan - Lid For Half Size', 74.25, 2.49);
insert into items (name, price, offer) values ('Salt - Seasoned', 99.41, 9.48);
insert into items (name, price, offer) values ('Table Cloth 81x81 White', 82.26, 3.16);
insert into items (name, price, offer) values ('Croissant, Raw - Mini', 3.85, 17.55);
insert into items (name, price, offer) values ('Salmon - Atlantic, Skin On', 49.41, 1.8);
insert into items (name, price, offer) values ('Shiro Miso', 25.55, 17.24);
insert into items (name, price, offer) values ('Pie Filling - Cherry', 40.55, 11.99);
insert into items (name, price, offer) values ('Pasta - Penne, Rigate, Dry', 64.14, 11.09);
insert into items (name, price, offer) values ('Beer - True North Strong Ale', 59.04, 10.21);
insert into items (name, price, offer) values ('Pineapple - Regular', 68.97, 14.29);
insert into items (name, price, offer) values ('Wine - Red, Marechal Foch', 40.8, 4.38);
insert into items (name, price, offer) values ('Yeast Dry - Fleischman', 74.15, 3.77);
insert into items (name, price, offer) values ('Pepper - Paprika, Hungarian', 51.83, 17.96);
insert into items (name, price, offer) values ('Carbonated Water - White Grape', 90.65, 7.51);
insert into items (name, price, offer) values ('Beans - Navy, Dry', 56.91, 5.63);
insert into items (name, price, offer) values ('Wine - Maipo Valle Cabernet', 19.06, 5.2);
insert into items (name, price, offer) values ('Chinese Lemon Pork', 20.86, 8.35);
insert into items (name, price, offer) values ('Mikes Hard Lemonade', 7.15, 7.97);
insert into items (name, price, offer) values ('Water - Mineral, Carbonated', 5.47, 10.69);
insert into items (name, price, offer) values ('Soup - Knorr, Chicken Gumbo', 1.88, 13.65);
insert into items (name, price, offer) values ('Ecolab - Ster Bac', 53.49, 12.57);
insert into items (name, price, offer) values ('Lemonade - Black Cherry, 591 Ml', 71.21, 13.26);
insert into items (name, price, offer) values ('Lamb - Ground', 6.23, 7.24);
insert into items (name, price, offer) values ('Hand Towel', 40.03, 10.22);
insert into items (name, price, offer) values ('Kellogs All Bran Bars', 69.27, 18.05);
insert into items (name, price, offer) values ('Steampan - Half Size Shallow', 63.24, 12.89);
insert into items (name, price, offer) values ('Garlic - Peeled', 27.36, 19.75);
insert into items (name, price, offer) values ('Galliano', 90.69, 6.31);
insert into items (name, price, offer) values ('Venison - Striploin', 79.79, 9.89);
insert into items (name, price, offer) values ('Tabasco Sauce, 2 Oz', 89.06, 19.96);
insert into items (name, price, offer) values ('Soup - Base Broth Chix', 5.07, 17.87);
insert into items (name, price, offer) values ('Gin - Gilbeys London, Dry', 97.87, 15.98);
insert into items (name, price, offer) values ('Halibut - Steaks', 20.19, 13.96);
insert into items (name, price, offer) values ('Wine - Pinot Grigio Collavini', 52.94, 11.99);
insert into items (name, price, offer) values ('Crab - Claws, 26 - 30', 39.18, 3.32);
insert into items (name, price, offer) values ('Potatoes - Yukon Gold 5 Oz', 2.63, 10.56);
insert into items (name, price, offer) values ('Pesto - Primerba, Paste', 37.23, 12.66);
insert into items (name, price, offer) values ('Pasta - Tortellini, Fresh', 3.99, 3.34);
insert into items (name, price, offer) values ('Kolrabi', 90.81, 12.35);
insert into items (name, price, offer) values ('Garbage Bag - Clear', 77.69, 12.05);
insert into items (name, price, offer) values ('Chicken Giblets', 87.37, 17.52);
insert into items (name, price, offer) values ('Pickle - Dill', 88.29, 14.2);
insert into items (name, price, offer) values ('Towels - Paper / Kraft', 93.88, 13.1);
insert into items (name, price, offer) values ('Wine - Cava Aria Estate Brut', 38.07, 17.86);
insert into items (name, price, offer) values ('Cookie Dough - Chocolate Chip', 31.81, 12.18);
insert into items (name, price, offer) values ('Oranges - Navel, 72', 12.75, 1.82);
insert into items (name, price, offer) values ('Flower - Dish Garden', 59.87, 11.59);
insert into items (name, price, offer) values ('Dried Cranberries', 72.67, 13.58);
insert into items (name, price, offer) values ('Island Oasis - Ice Cream Mix', 71.39, 14.75);
insert into items (name, price, offer) values ('Bread - Raisin', 58.44, 16.56);
insert into items (name, price, offer) values ('Sugar - White Packet', 25.13, 17.48);
insert into items (name, price, offer) values ('Wine - Maipo Valle Cabernet', 68.99, 1.62);
insert into items (name, price, offer) values ('Sponge Cake Mix - Chocolate', 79.31, 18.97);
insert into items (name, price, offer) values ('Wine - Vidal Icewine Magnotta', 41.52, 8.34);
insert into items (name, price, offer) values ('Rootbeer', 16.45, 3.19);
insert into items (name, price, offer) values ('Pepper Squash', 34.89, 14.96);
insert into items (name, price, offer) values ('Plums - Red', 75.8, 10.27);
insert into items (name, price, offer) values ('Foam Espresso Cup Plain White', 71.05, 17.23);
insert into items (name, price, offer) values ('Veal - Leg', 17.15, 3.82);
insert into items (name, price, offer) values ('Kellogs All Bran Bars', 93.54, 17.3);
insert into items (name, price, offer) values ('Olives - Nicoise', 41.16, 17.95);
insert into items (name, price, offer) values ('Wine - Barbera Alba Doc 2001', 44.71, 7.01);
insert into items (name, price, offer) values ('Coffee Decaf Colombian', 99.19, 10.24);
insert into items (name, price, offer) values ('Paper - Brown Paper Mini Cups', 39.06, 10.03);
insert into items (name, price, offer) values ('Sauce - Chili', 7.54, 1.86);
insert into items (name, price, offer) values ('Bread - Pita', 57.5, 12.4);
insert into items (name, price, offer) values ('Buffalo - Short Rib Fresh', 46.27, 1.8);
insert into items (name, price, offer) values ('Spaghetti Squash', 24.26, 6.91);
insert into items (name, price, offer) values ('Wine - Gewurztraminer Pierre', 87.86, 3.74);
insert into items (name, price, offer) values ('Soup - Boston Clam Chowder', 52.47, 6.64);
insert into items (name, price, offer) values ('Wine - Penfolds Koonuga Hill', 23.05, 11.66);
insert into items (name, price, offer) values ('Pasta - Spaghetti, Dry', 67.74, 8.81);
insert into items (name, price, offer) values ('Sugar - Crumb', 12.66, 6.66);
insert into items (name, price, offer) values ('Mousse - Mango', 33.11, 5.48);
insert into items (name, price, offer) values ('Truffle - Peelings', 98.49, 4.77);
insert into items (name, price, offer) values ('Southern Comfort', 77.37, 1.89);
insert into items (name, price, offer) values ('Pepper - Cayenne', 67.42, 18.22);
insert into items (name, price, offer) values ('Rye Special Old', 69.78, 13.94);
insert into items (name, price, offer) values ('Sambuca Cream', 9.59, 18.7);
insert into items (name, price, offer) values ('Sauce Bbq Smokey', 85.63, 7.69);
insert into items (name, price, offer) values ('Jam - Raspberry,jar', 85.12, 6.84);
insert into items (name, price, offer) values ('Pail - 15l White, With Handle', 8.8, 11.07);
insert into items (name, price, offer) values ('Lotus Root', 64.34, 7.3);
insert into items (name, price, offer) values ('Wine - Red, Mouton Cadet', 70.26, 13.04);
insert into items (name, price, offer) values ('Tomatoes Tear Drop', 7.51, 1.5);
insert into items (name, price, offer) values ('Coffee Cup 12oz 5342cd', 67.76, 6.81);
insert into items (name, price, offer) values ('Turkey - Whole, Fresh', 13.4, 17.45);
insert into items (name, price, offer) values ('Mudslide', 25.74, 9.44);
insert into items (name, price, offer) values ('Apple - Granny Smith', 29.81, 19.44);
insert into items (name, price, offer) values ('Pasta - Penne, Rigate, Dry', 47.34, 2.82);
insert into items (name, price, offer) values ('Asparagus - Green, Fresh', 94.17, 1.34);
insert into items (name, price, offer) values ('Bread - Bagels, Mini', 64.39, 19.05);
insert into items (name, price, offer) values ('Beef - Short Ribs', 30.05, 7.84);
insert into items (name, price, offer) values ('Sauce - Rosee', 60.26, 7.42);
insert into items (name, price, offer) values ('Nut - Pistachio, Shelled', 53.05, 17.77);
insert into items (name, price, offer) values ('Bread - Burger', 86.82, 18.35);
insert into items (name, price, offer) values ('Artichoke - Fresh', 15.2, 1.97);
insert into items (name, price, offer) values ('Pails With Lids', 91.53, 19.16);
insert into items (name, price, offer) values ('Bowl 12 Oz - Showcase 92012', 14.04, 8.2);
insert into items (name, price, offer) values ('Wine - Sake', 51.88, 19.12);
insert into items (name, price, offer) values ('Pasta - Penne, Rigate, Dry', 80.57, 17.75);
insert into items (name, price, offer) values ('Apple - Royal Gala', 92.04, 13.58);
insert into items (name, price, offer) values ('Canada Dry', 69.02, 13.63);
insert into items (name, price, offer) values ('Rolled Oats', 90.62, 5.42);
insert into items (name, price, offer) values ('Gooseberry', 53.77, 16.41);
insert into items (name, price, offer) values ('Danishes - Mini Raspberry', 36.31, 18.15);
insert into items (name, price, offer) values ('Mussels - Frozen', 73.48, 12.5);
insert into items (name, price, offer) values ('Oil - Grapeseed Oil', 3.97, 19.18);
insert into items (name, price, offer) values ('Pastry - Trippleberry Muffin - Mini', 88.89, 1.17);
insert into items (name, price, offer) values ('Steampan Lid', 23.21, 13.15);
insert into items (name, price, offer) values ('Juice - Clam, 46 Oz', 87.12, 18.26);
insert into items (name, price, offer) values ('Pears - Bartlett', 28.5, 11.08);
insert into items (name, price, offer) values ('Lamb - Whole, Frozen', 12.06, 19.61);
insert into items (name, price, offer) values ('Scallops - 10/20', 55.55, 2.63);
insert into items (name, price, offer) values ('Crush - Cream Soda', 38.01, 13.37);
insert into items (name, price, offer) values ('Grand Marnier', 12.01, 13.21);
insert into items (name, price, offer) values ('Milk - Chocolate 250 Ml', 58.39, 12.62);
insert into items (name, price, offer) values ('Cookies Cereal Nut', 64.2, 18.13);
insert into items (name, price, offer) values ('Coffee - Decaffeinato Coffee', 87.48, 18.12);
insert into items (name, price, offer) values ('Sprouts - Onion', 42.78, 3.29);
insert into items (name, price, offer) values ('Hand Towel', 88.18, 6.59);
insert into items (name, price, offer) values ('Orange - Canned, Mandarin', 23.11, 13.57);
insert into items (name, price, offer) values ('Cumin - Whole', 71.84, 2.15);
insert into items (name, price, offer) values ('Parsley - Dried', 69.96, 8.93);
insert into items (name, price, offer) values ('Bacardi Raspberry', 47.13, 17.79);
insert into items (name, price, offer) values ('Sole - Iqf', 99.01, 11.56);
insert into items (name, price, offer) values ('Wine - Taylors Reserve', 50.97, 18.19);
insert into items (name, price, offer) values ('Crush - Orange, 355ml', 98.44, 9.44);
insert into items (name, price, offer) values ('Pastry - Choclate Baked', 2.41, 4.08);
insert into items (name, price, offer) values ('Longos - Cheese Tortellini', 42.17, 5.03);
insert into items (name, price, offer) values ('Tray - 16in Rnd Blk', 71.48, 5.06);
insert into items (name, price, offer) values ('Star Anise, Whole', 44.15, 16.02);
insert into items (name, price, offer) values ('Chestnuts - Whole,canned', 25.4, 11.26);
insert into items (name, price, offer) values ('Tomatoes - Diced, Canned', 87.61, 16.28);
insert into items (name, price, offer) values ('Kellogs Cereal In A Cup', 2.25, 8.28);
insert into items (name, price, offer) values ('Banana', 76.53, 1.02);
insert into items (name, price, offer) values ('Sugar - Individual Portions', 39.71, 5.08);
insert into items (name, price, offer) values ('Pastry - Key Limepoppy Seed Tea', 29.12, 16.84);
insert into items (name, price, offer) values ('Beef - Inside Round', 50.02, 10.52);
insert into items (name, price, offer) values ('Seedlings - Clamshell', 20.6, 4.23);
insert into items (name, price, offer) values ('Relish', 1.43, 10.87);
insert into items (name, price, offer) values ('Mushroom - Chantrelle, Fresh', 20.89, 3.53);
insert into items (name, price, offer) values ('Wine - Coteaux Du Tricastin Ac', 13.82, 8.34);
insert into items (name, price, offer) values ('Milk - Buttermilk', 92.92, 2.38);
insert into items (name, price, offer) values ('Wine - Magnotta - Cab Franc', 63.38, 3.78);
insert into items (name, price, offer) values ('Emulsifier', 7.3, 3.2);
insert into items (name, price, offer) values ('Venison - Ground', 56.87, 9.77);
insert into items (name, price, offer) values ('Tamarind Paste', 77.42, 7.65);
insert into items (name, price, offer) values ('Sugar - Crumb', 32.91, 7.15);
insert into items (name, price, offer) values ('Flour - Fast / Rapid', 86.94, 6.18);
insert into items (name, price, offer) values ('Sprite - 355 Ml', 42.19, 14.01);
insert into items (name, price, offer) values ('Chocolate - White', 21.1, 1.09);
insert into items (name, price, offer) values ('Danishes - Mini Cheese', 81.3, 12.72);
insert into items (name, price, offer) values ('Chinese Lemon Pork', 55.72, 18.81);
insert into items (name, price, offer) values ('Whmis Spray Bottle Graduated', 45.92, 6.52);
insert into items (name, price, offer) values ('Puff Pastry - Sheets', 11.13, 19.49);
insert into items (name, price, offer) values ('Lamb Leg - Bone - In Nz', 62.53, 17.13);
insert into items (name, price, offer) values ('Salmon - Whole, 4 - 6 Pounds', 57.86, 17.27);
insert into items (name, price, offer) values ('Venison - Racks Frenched', 23.77, 8.99);
insert into items (name, price, offer) values ('Quail - Whole, Bone - In', 75.39, 5.27);
insert into items (name, price, offer) values ('Soup - Verve - Chipotle Chicken', 56.63, 4.06);
insert into items (name, price, offer) values ('Garbage Bags - Clear', 5.48, 7.85);
insert into items (name, price, offer) values ('Phyllo Dough', 92.9, 11.59);
insert into items (name, price, offer) values ('Squash - Pattypan, Yellow', 2.14, 19.12);
insert into items (name, price, offer) values ('Cheese - Swiss Sliced', 94.7, 9.37);
insert into items (name, price, offer) values ('Cake - Bande Of Fruit', 50.18, 13.92);
insert into items (name, price, offer) values ('Milk - Buttermilk', 80.73, 19.24);
insert into items (name, price, offer) values ('Beef - Roasted, Cooked', 24.76, 5.11);
insert into items (name, price, offer) values ('Bar Bran Honey Nut', 59.85, 11.83);
insert into items (name, price, offer) values ('Pork Casing', 61.62, 13.71);
insert into items (name, price, offer) values ('Wasabi Powder', 80.93, 4.09);
insert into items (name, price, offer) values ('Tabasco Sauce, 2 Oz', 99.15, 15.09);
insert into items (name, price, offer) values ('Wine - Carmenere Casillero Del', 96.08, 8.64);
insert into items (name, price, offer) values ('Mustard Prepared', 99.91, 4.09);
insert into items (name, price, offer) values ('Beef Striploin Aaa', 66.61, 2.61);
insert into items (name, price, offer) values ('Butter - Salted, Micro', 78.96, 15.74);
insert into items (name, price, offer) values ('Tarragon - Fresh', 58.87, 18.63);
insert into items (name, price, offer) values ('Whmis - Spray Bottle Trigger', 34.44, 19.64);
insert into items (name, price, offer) values ('Coffee - Decafenated', 20.51, 15.51);
insert into items (name, price, offer) values ('Wine - Red, Gallo, Merlot', 94.9, 5.7);
insert into items (name, price, offer) values ('Salmon - Canned', 66.34, 3.4);
insert into items (name, price, offer) values ('Pasta - Fettuccine, Dry', 17.37, 7.64);
insert into items (name, price, offer) values ('Mackerel Whole Fresh', 24.38, 16.1);
insert into items (name, price, offer) values ('Flower - Leather Leaf Fern', 14.03, 11.63);
insert into items (name, price, offer) values ('Wine - Red, Marechal Foch', 37.14, 17.01);
insert into items (name, price, offer) values ('Sprite - 355 Ml', 87.83, 17.38);
insert into items (name, price, offer) values ('Tomato - Green', 84.74, 16.55);
insert into items (name, price, offer) values ('Worcestershire Sauce', 63.59, 1.95);
insert into items (name, price, offer) values ('Bag - Clear 7 Lb', 74.79, 18.02);
insert into items (name, price, offer) values ('Lettuce - Romaine', 50.2, 18.68);
insert into items (name, price, offer) values ('Cheese - Grie Des Champ', 4.67, 19.14);
insert into items (name, price, offer) values ('Burger Veggie', 67.25, 18.1);
insert into items (name, price, offer) values ('Towels - Paper / Kraft', 16.06, 15.14);
insert into items (name, price, offer) values ('Beer - Upper Canada Light', 14.55, 2.66);
insert into items (name, price, offer) values ('Bread - Sour Sticks With Onion', 89.29, 18.95);
insert into items (name, price, offer) values ('Juice - V8 Splash', 5.07, 10.92);
insert into items (name, price, offer) values ('Pork - Backs - Boneless', 70.99, 17.65);
insert into items (name, price, offer) values ('Bread - Multigrain Oval', 80.89, 1.08);
insert into items (name, price, offer) values ('Bread - White Mini Epi', 79.5, 18.94);
insert into items (name, price, offer) values ('Bread - Italian Sesame Poly', 14.51, 19.78);
insert into items (name, price, offer) values ('Chocolate - Unsweetened', 8.06, 17.82);
insert into items (name, price, offer) values ('Sun - Dried Tomatoes', 41.45, 8.25);
insert into items (name, price, offer) values ('Wine - Chardonnay Mondavi', 25.72, 8.22);
insert into items (name, price, offer) values ('Bols Melon Liqueur', 44.81, 12.15);
insert into items (name, price, offer) values ('Cup - 3.5oz, Foam', 24.47, 19.29);
insert into items (name, price, offer) values ('Yogurt - Strawberry, 175 Gr', 66.7, 8.6);
insert into items (name, price, offer) values ('Wine - Duboeuf Beaujolais', 62.57, 8.79);
insert into items (name, price, offer) values ('Peppercorns - Green', 78.89, 15.35);
insert into items (name, price, offer) values ('Veal - Chops, Split, Frenched', 26.95, 10.95);
insert into items (name, price, offer) values ('Orange Roughy 4/6 Oz', 53.83, 1.01);
insert into items (name, price, offer) values ('Pastry - Chocolate Marble Tea', 25.69, 13.91);
insert into items (name, price, offer) values ('Wine - Chateau Aqueria Tavel', 55.83, 5.28);
insert into items (name, price, offer) values ('Vaccum Bag - 14x20', 96.83, 6.47);
insert into items (name, price, offer) values ('Meldea Green Tea Liquor', 27.26, 4.01);
insert into items (name, price, offer) values ('Knife Plastic - White', 52.28, 16.85);
insert into items (name, price, offer) values ('Mix - Cocktail Strawberry Daiquiri', 1.2, 16.0);
insert into items (name, price, offer) values ('Cognac - Courvaisier', 55.12, 5.13);
insert into items (name, price, offer) values ('Wine - Maipo Valle Cabernet', 47.05, 1.21);
insert into items (name, price, offer) values ('Wine - Sogrape Mateus Rose', 84.51, 4.87);
insert into items (name, price, offer) values ('Buffalo - Tenderloin', 8.62, 8.64);
insert into items (name, price, offer) values ('Pastry - Raisin Muffin - Mini', 14.08, 16.72);
insert into items (name, price, offer) values ('Coffee - Almond Amaretto', 91.72, 1.6);
insert into items (name, price, offer) values ('Ice Cream Bar - Drumstick', 49.55, 13.1);
insert into items (name, price, offer) values ('Shallots', 15.51, 9.36);
insert into items (name, price, offer) values ('Wine - White, Gewurtzraminer', 86.92, 18.84);
insert into items (name, price, offer) values ('Yogurt - Banana, 175 Gr', 57.47, 15.93);
insert into items (name, price, offer) values ('Bread - Roll, Whole Wheat', 88.65, 17.44);
insert into items (name, price, offer) values ('Crackers - Trio', 53.87, 6.19);
insert into items (name, price, offer) values ('Tomatoes - Grape', 43.26, 5.45);
insert into items (name, price, offer) values ('Bacardi Raspberry', 1.02, 2.32);
insert into items (name, price, offer) values ('Juice - Clam, 46 Oz', 85.35, 10.22);
insert into items (name, price, offer) values ('Iced Tea Concentrate', 55.47, 9.33);
insert into items (name, price, offer) values ('Shrimp - Tiger 21/25', 21.8, 6.68);
insert into items (name, price, offer) values ('Bread - Pullman, Sliced', 73.56, 18.35);
insert into items (name, price, offer) values ('Cake - Box Window 10x10x2.5', 8.95, 17.75);
insert into items (name, price, offer) values ('Pork - Inside', 25.85, 18.11);
insert into items (name, price, offer) values ('Plastic Arrow Stir Stick', 18.25, 9.91);
insert into items (name, price, offer) values ('Capon - Breast, Double, Wing On', 28.04, 5.71);
insert into items (name, price, offer) values ('Mushroom - Shitake, Fresh', 54.68, 10.81);
insert into items (name, price, offer) values ('Ostrich - Fan Fillet', 26.72, 2.81);
insert into items (name, price, offer) values ('Muffin Hinge Container 6', 76.02, 5.44);
insert into items (name, price, offer) values ('Onions Granulated', 23.33, 14.97);
insert into items (name, price, offer) values ('Cheese - Havarti, Roasted Garlic', 92.83, 6.4);
insert into items (name, price, offer) values ('Beets - Candy Cane, Organic', 71.05, 2.18);
insert into items (name, price, offer) values ('Capon - Breast, Wing On', 53.78, 12.6);
insert into items (name, price, offer) values ('Nantucket - Carrot Orange', 94.04, 4.73);
insert into items (name, price, offer) values ('Coffee - Espresso', 72.82, 8.11);
insert into items (name, price, offer) values ('Pasta - Canelloni', 61.64, 3.13);
insert into items (name, price, offer) values ('Truffle - Peelings', 40.33, 3.01);
insert into items (name, price, offer) values ('Dill Weed - Fresh', 45.25, 8.66);
insert into items (name, price, offer) values ('Bread - Dark Rye', 48.49, 13.39);
insert into items (name, price, offer) values ('Mushroom - King Eryingii', 69.49, 17.16);
insert into items (name, price, offer) values ('Vodka - Lemon, Absolut', 46.58, 5.09);
insert into items (name, price, offer) values ('Curry Powder Madras', 95.84, 13.93);
insert into items (name, price, offer) values ('Wonton Wrappers', 85.88, 9.97);
insert into items (name, price, offer) values ('Daikon Radish', 56.71, 5.03);
insert into items (name, price, offer) values ('Sauerkraut', 2.13, 5.52);
insert into items (name, price, offer) values ('Cheese - Provolone', 80.76, 9.78);
insert into items (name, price, offer) values ('Tea - Darjeeling, Azzura', 71.69, 6.21);
insert into items (name, price, offer) values ('Anchovy In Oil', 13.08, 8.13);
insert into items (name, price, offer) values ('Hold Up Tool Storage Rack', 93.33, 5.35);
insert into items (name, price, offer) values ('Wine - Prosecco Valdobienne', 33.57, 18.43);
insert into items (name, price, offer) values ('Bowl 12 Oz - Showcase 92012', 85.07, 2.8);
insert into items (name, price, offer) values ('Wanton Wrap', 11.17, 17.64);
insert into items (name, price, offer) values ('Beets - Pickled', 26.81, 1.94);
insert into items (name, price, offer) values ('Pomello', 60.47, 6.88);
insert into items (name, price, offer) values ('Veal - Ground', 37.02, 19.15);
insert into items (name, price, offer) values ('Capers - Pickled', 5.16, 19.28);
insert into items (name, price, offer) values ('Wine - Duboeuf Beaujolais', 48.62, 3.12);
insert into items (name, price, offer) values ('Tomatoes - Yellow Hot House', 35.94, 15.14);
insert into items (name, price, offer) values ('Lamb - Sausage Casings', 66.39, 1.7);
insert into items (name, price, offer) values ('Gooseberry', 89.29, 16.4);
insert into items (name, price, offer) values ('Beef Flat Iron Steak', 37.42, 8.12);
insert into items (name, price, offer) values ('Basil - Fresh', 58.65, 1.26);
insert into items (name, price, offer) values ('Truffle Cups - Brown', 97.67, 18.14);
insert into items (name, price, offer) values ('Vodka - Lemon, Absolut', 82.8, 8.86);
insert into items (name, price, offer) values ('Coffee - Almond Amaretto', 36.03, 2.01);
insert into items (name, price, offer) values ('Wine - Pinot Noir Mondavi Coastal', 94.01, 11.04);
insert into items (name, price, offer) values ('Wine - Barolo Fontanafredda', 84.31, 11.47);
insert into items (name, price, offer) values ('Wine - Placido Pinot Grigo', 17.37, 12.36);
insert into items (name, price, offer) values ('Wine - Merlot Vina Carmen', 54.17, 8.76);
insert into items (name, price, offer) values ('Oil - Food, Lacquer Spray', 57.54, 4.85);
insert into items (name, price, offer) values ('Soup - Knorr, French Onion', 86.87, 18.07);
insert into items (name, price, offer) values ('Jello - Assorted', 23.43, 7.3);
insert into items (name, price, offer) values ('Steampan Lid', 96.38, 16.07);
insert into items (name, price, offer) values ('Cheese - Brie, Triple Creme', 35.07, 10.67);
insert into items (name, price, offer) values ('Bandage - Flexible Neon', 47.82, 15.9);
insert into items (name, price, offer) values ('Chicken - Base', 2.78, 12.79);
insert into items (name, price, offer) values ('Garlic - Elephant', 5.35, 6.49);
insert into items (name, price, offer) values ('Strawberries', 19.7, 2.92);
insert into items (name, price, offer) values ('Grenadine', 7.88, 10.26);
insert into items (name, price, offer) values ('Puree - Passion Fruit', 46.86, 17.36);
insert into items (name, price, offer) values ('Milk - Chocolate 500ml', 63.66, 5.01);
insert into items (name, price, offer) values ('Cookies - Englishbay Oatmeal', 84.37, 14.14);
insert into items (name, price, offer) values ('Chicken - Leg, Fresh', 11.96, 3.28);
insert into items (name, price, offer) values ('Appetiser - Bought', 77.25, 8.24);
insert into items (name, price, offer) values ('Juice - Cranberry 284ml', 48.27, 5.51);
insert into items (name, price, offer) values ('Plasticknivesblack', 63.03, 10.85);
insert into items (name, price, offer) values ('Mcgillicuddy Vanilla Schnap', 22.43, 15.06);
insert into items (name, price, offer) values ('Sugar - Brown', 97.77, 9.94);
insert into items (name, price, offer) values ('Rum - Cream, Amarula', 33.88, 16.72);
insert into items (name, price, offer) values ('Island Oasis - Cappucino Mix', 37.9, 19.13);
insert into items (name, price, offer) values ('Pie Filling - Pumpkin', 16.49, 13.72);
insert into items (name, price, offer) values ('Pasta - Lasagne, Fresh', 46.9, 2.56);
insert into items (name, price, offer) values ('Beef - Shank', 9.18, 19.94);
insert into items (name, price, offer) values ('Bandage - Flexible Neon', 23.24, 5.06);
insert into items (name, price, offer) values ('Yogurt - Strawberry, 175 Gr', 15.22, 3.33);
insert into items (name, price, offer) values ('Fish - Halibut, Cold Smoked', 13.87, 11.67);
insert into items (name, price, offer) values ('Sprite - 355 Ml', 5.32, 13.51);
insert into items (name, price, offer) values ('Longos - Cheese Tortellini', 41.96, 2.89);
insert into items (name, price, offer) values ('Chocolate Liqueur - Godet White', 6.6, 3.76);
insert into items (name, price, offer) values ('Carbonated Water - Wildberry', 32.54, 9.53);
insert into items (name, price, offer) values ('Stock - Beef, Brown', 97.51, 19.94);
insert into items (name, price, offer) values ('Juice - Apple, 500 Ml', 89.52, 1.41);
insert into items (name, price, offer) values ('Longos - Grilled Salmon With Bbq', 46.59, 12.75);
insert into items (name, price, offer) values ('Rice Wine - Aji Mirin', 27.51, 17.02);
insert into items (name, price, offer) values ('Flour - Semolina', 92.75, 12.43);
insert into items (name, price, offer) values ('Shrimp - 16 - 20 Cooked, Peeled', 67.23, 1.51);
insert into items (name, price, offer) values ('Carbonated Water - Wildberry', 52.03, 3.84);
insert into items (name, price, offer) values ('Coffee - Ristretto Coffee Capsule', 55.92, 1.27);
insert into items (name, price, offer) values ('Juice - Tomato, 10 Oz', 78.43, 15.84);
insert into items (name, price, offer) values ('Fond - Neutral', 48.58, 13.07);
insert into items (name, price, offer) values ('Potatoes - Mini White 3 Oz', 74.83, 3.14);
insert into items (name, price, offer) values ('Wine - Saint - Bris 2002, Sauv', 62.21, 11.84);
insert into items (name, price, offer) values ('Beer - Blue', 66.97, 6.6);
insert into items (name, price, offer) values ('Sour Cream', 74.54, 5.95);
insert into items (name, price, offer) values ('Soap - Pine Sol Floor Cleaner', 36.08, 9.84);
insert into items (name, price, offer) values ('Ice Cream - Life Savers', 98.43, 17.16);
insert into items (name, price, offer) values ('Pears - Bosc', 40.86, 19.95);
insert into items (name, price, offer) values ('Pate - Liver', 62.27, 9.82);
insert into items (name, price, offer) values ('Beef - Tender Tips', 10.75, 8.39);
insert into items (name, price, offer) values ('Carbonated Water - Cherry', 69.55, 14.57);
insert into items (name, price, offer) values ('Venison - Racks Frenched', 46.67, 7.88);
insert into items (name, price, offer) values ('Sugar - Icing', 45.92, 3.3);
insert into items (name, price, offer) values ('Salt And Pepper Mix - White', 1.38, 11.2);
insert into items (name, price, offer) values ('Wine - White, Mosel Gold', 28.37, 15.56);
insert into items (name, price, offer) values ('Juice - Orangina', 34.04, 11.52);
insert into items (name, price, offer) values ('Buttons', 70.95, 1.55);
insert into items (name, price, offer) values ('Seedlings - Mix, Organic', 86.6, 16.67);
insert into items (name, price, offer) values ('Wine - Muscadet Sur Lie', 85.42, 5.45);
insert into items (name, price, offer) values ('Eggwhite Frozen', 17.36, 12.28);
insert into items (name, price, offer) values ('Foil - 4oz Custard Cup', 56.57, 8.09);
insert into items (name, price, offer) values ('Tomatoes - Diced, Canned', 5.4, 11.67);
insert into items (name, price, offer) values ('Soda Water - Club Soda, 355 Ml', 79.37, 8.81);
insert into items (name, price, offer) values ('Salad Dressing', 61.49, 3.13);
insert into items (name, price, offer) values ('Tuna - Bluefin', 5.69, 6.4);
insert into items (name, price, offer) values ('Table Cloth 120 Round White', 6.28, 11.27);
insert into items (name, price, offer) values ('General Purpose Trigger', 12.45, 8.52);
insert into items (name, price, offer) values ('Tea - Camomele', 88.86, 6.6);
insert into items (name, price, offer) values ('Bread - English Muffin', 41.91, 1.81);
insert into items (name, price, offer) values ('Wine - Chateau Bonnet', 28.08, 16.53);
insert into items (name, price, offer) values ('Wine - Chateau Bonnet', 34.17, 3.12);
insert into items (name, price, offer) values ('Cheese - Marble', 32.62, 1.41);
insert into items (name, price, offer) values ('Wine - Sake', 32.73, 19.89);
insert into items (name, price, offer) values ('Pork - Bacon Cooked Slcd', 41.85, 18.27);
insert into items (name, price, offer) values ('Cakes Assorted', 66.67, 8.51);
insert into items (name, price, offer) values ('Nut - Peanut, Roasted', 32.67, 13.6);
insert into items (name, price, offer) values ('Cheese - Cheddar, Old White', 61.73, 8.29);
insert into items (name, price, offer) values ('Calvados - Boulard', 78.57, 13.1);
insert into items (name, price, offer) values ('Wine - White, Antinore Orvieto', 64.16, 3.51);
insert into items (name, price, offer) values ('Carrots - Mini, Stem On', 35.89, 6.38);
insert into items (name, price, offer) values ('Mushroom - King Eryingii', 76.9, 10.7);
insert into items (name, price, offer) values ('Egg - Salad Premix', 63.86, 3.44);
insert into items (name, price, offer) values ('Soup - Campbells Broccoli', 65.37, 3.12);
insert into items (name, price, offer) values ('Wine - Chablis 2003 Champs', 42.1, 1.7);
insert into items (name, price, offer) values ('Pepper - Chilli Seeds Mild', 3.71, 3.81);
insert into items (name, price, offer) values ('Sauce - Gravy, Au Jus, Mix', 71.89, 8.09);
insert into items (name, price, offer) values ('Water Chestnut - Canned', 14.72, 9.15);
insert into items (name, price, offer) values ('Juice - Happy Planet', 82.49, 7.9);
insert into items (name, price, offer) values ('Curry Powder', 85.11, 1.15);
insert into items (name, price, offer) values ('Mangoes', 34.19, 14.32);
insert into items (name, price, offer) values ('Bread Foccacia Whole', 82.13, 5.54);
insert into items (name, price, offer) values ('Onions - Dried, Chopped', 64.41, 12.72);
insert into items (name, price, offer) values ('Eggs - Extra Large', 28.12, 9.84);
insert into items (name, price, offer) values ('Plastic Wrap', 58.65, 13.34);
insert into items (name, price, offer) values ('The Pop Shoppe - Black Cherry', 83.28, 11.45);
insert into items (name, price, offer) values ('Trueblue - Blueberry 12x473ml', 44.56, 16.46);
insert into items (name, price, offer) values ('Juice - Apple 284ml', 78.36, 3.39);
insert into items (name, price, offer) values ('Beef - Outside, Round', 8.3, 5.55);
insert into items (name, price, offer) values ('Goldschalger', 24.23, 8.38);
insert into items (name, price, offer) values ('Appetizer - Cheese Bites', 69.83, 17.65);
insert into items (name, price, offer) values ('Tomatoes - Plum, Canned', 62.37, 12.48);
insert into items (name, price, offer) values ('Bread - Italian Corn Meal Poly', 80.14, 9.54);
insert into items (name, price, offer) values ('Sunflower Seed Raw', 77.85, 5.44);
insert into items (name, price, offer) values ('Longos - Chicken Curried', 73.31, 9.28);
insert into items (name, price, offer) values ('Turkey - Ground. Lean', 17.07, 16.81);
insert into items (name, price, offer) values ('Wine - Carmenere Casillero Del', 95.74, 2.97);
insert into items (name, price, offer) values ('Wine - Magnotta - Cab Franc', 43.71, 16.56);
insert into items (name, price, offer) values ('Wine - Sherry Dry Sack, William', 98.14, 19.13);
insert into items (name, price, offer) values ('Soup V8 Roasted Red Pepper', 57.15, 13.23);
insert into items (name, price, offer) values ('Container - Foam Dixie 12 Oz', 1.71, 4.97);
insert into items (name, price, offer) values ('Bread Fig And Almond', 66.61, 8.62);
insert into items (name, price, offer) values ('Muffin Mix - Raisin Bran', 4.34, 4.99);
insert into items (name, price, offer) values ('Chicken - White Meat, No Tender', 94.42, 10.91);
insert into items (name, price, offer) values ('Chicken - Whole Fryers', 37.62, 4.73);
insert into items (name, price, offer) values ('Pepper - Chilli Seeds Mild', 65.45, 15.46);
insert into items (name, price, offer) values ('Ice - Clear, 300 Lb For Carving', 23.41, 16.0);
insert into items (name, price, offer) values ('Mushroom Morel Fresh', 62.79, 8.66);
insert into items (name, price, offer) values ('Container - Foam Dixie 12 Oz', 26.27, 9.44);
insert into items (name, price, offer) values ('Muffin Batt - Blueberry Passion', 40.98, 1.8);
insert into items (name, price, offer) values ('Turkey - Oven Roast Breast', 21.53, 12.91);
insert into items (name, price, offer) values ('Rice - Wild', 91.22, 4.72);
insert into items (name, price, offer) values ('Rabbit - Frozen', 58.46, 8.7);
insert into items (name, price, offer) values ('Taro Root', 17.49, 6.56);
insert into items (name, price, offer) values ('Salmon - Smoked, Sliced', 83.26, 19.67);
insert into items (name, price, offer) values ('Shopper Bag - S - 4', 13.71, 7.29);
insert into items (name, price, offer) values ('V8 Pet', 7.69, 18.35);
insert into items (name, price, offer) values ('Appetizer - Escargot Puff', 47.58, 6.92);
insert into items (name, price, offer) values ('Lady Fingers', 3.08, 15.95);
insert into items (name, price, offer) values ('Eggroll', 98.22, 5.52);
insert into items (name, price, offer) values ('Rice - Basmati', 8.77, 13.89);
insert into items (name, price, offer) values ('Bread - Raisin Walnut Oval', 68.33, 4.53);
insert into items (name, price, offer) values ('Steam Pan - Half Size Deep', 15.12, 15.31);
insert into items (name, price, offer) values ('Wine - Bourgogne 2002, La', 93.3, 13.3);
insert into items (name, price, offer) values ('The Pop Shoppe Pinapple', 66.36, 5.91);
insert into items (name, price, offer) values ('Pepper - Green, Chili', 48.58, 17.38);
insert into items (name, price, offer) values ('Sugar - Brown', 42.18, 1.92);
insert into items (name, price, offer) values ('Cream - 10%', 55.37, 6.31);
insert into items (name, price, offer) values ('Cinnamon Buns Sticky', 70.42, 5.97);
insert into items (name, price, offer) values ('Wiberg Cure', 37.75, 5.76);
insert into items (name, price, offer) values ('Eel - Smoked', 28.17, 2.81);
insert into items (name, price, offer) values ('Beef - Ox Tongue', 40.22, 8.1);
insert into items (name, price, offer) values ('Puree - Mango', 45.14, 10.6);
insert into items (name, price, offer) values ('Green Tea Refresher', 7.73, 11.44);
insert into items (name, price, offer) values ('Bread - Pain Au Liat X12', 5.4, 11.82);
insert into items (name, price, offer) values ('Schnappes - Peach, Walkers', 22.74, 17.42);
insert into items (name, price, offer) values ('Beans - Black Bean, Preserved', 48.24, 13.67);
insert into items (name, price, offer) values ('Extract - Rum', 89.65, 14.61);
insert into items (name, price, offer) values ('Snapple - Iced Tea Peach', 85.39, 1.84);
insert into items (name, price, offer) values ('Wine - Ruffino Chianti', 63.25, 9.42);
insert into items (name, price, offer) values ('Tuna - Bluefin', 66.15, 18.39);
insert into items (name, price, offer) values ('Cardamon Seed / Pod', 79.5, 13.8);
insert into items (name, price, offer) values ('Celery Root', 63.48, 2.17);
insert into items (name, price, offer) values ('Vinegar - Raspberry', 94.64, 4.73);
insert into items (name, price, offer) values ('Melon - Honey Dew', 39.04, 12.1);
insert into items (name, price, offer) values ('Wine - White, Ej', 12.76, 10.17);
insert into items (name, price, offer) values ('Dill Weed - Dry', 51.48, 2.97);
insert into items (name, price, offer) values ('Flower - Carnations', 5.39, 13.17);
insert into items (name, price, offer) values ('Tequila - Sauza Silver', 88.16, 8.88);
insert into items (name, price, offer) values ('Water Chestnut - Canned', 16.68, 6.62);
insert into items (name, price, offer) values ('Chicken - Livers', 52.35, 9.76);
insert into items (name, price, offer) values ('Apron', 54.13, 14.77);
insert into items (name, price, offer) values ('Buffalo - Striploin', 1.56, 12.35);
insert into items (name, price, offer) values ('Chocolate - Milk, Callets', 58.16, 19.69);
insert into items (name, price, offer) values ('Truffle Paste', 97.13, 11.7);
insert into items (name, price, offer) values ('Flower - Dish Garden', 64.0, 17.15);
insert into items (name, price, offer) values ('Gloves - Goldtouch Disposable', 46.03, 6.12);
insert into items (name, price, offer) values ('Lobster - Tail, 3 - 4 Oz', 14.18, 5.69);
insert into items (name, price, offer) values ('Beans - Fava Fresh', 76.26, 2.16);
insert into items (name, price, offer) values ('Chocolate - Milk', 48.35, 13.49);
insert into items (name, price, offer) values ('Muffin Mix - Blueberry', 69.64, 18.68);
insert into items (name, price, offer) values ('Puree - Kiwi', 5.1, 12.98);
insert into items (name, price, offer) values ('Seabream Whole Farmed', 50.05, 8.61);
insert into items (name, price, offer) values ('Ham - Cooked Bayonne Tinned', 94.7, 19.05);
insert into items (name, price, offer) values ('Chicken - Thigh, Bone In', 24.21, 5.5);
insert into items (name, price, offer) values ('Pasta - Bauletti, Chicken White', 3.04, 15.33);
insert into items (name, price, offer) values ('Fondant - Icing', 23.8, 13.16);
insert into items (name, price, offer) values ('Venison - Racks Frenched', 75.86, 3.57);
